import { useState,type FormEvent } from 'react';
import { Link } from 'react-router-dom';
import { Plus,Download,Upload,Settings,History,Trash2 } from 'lucide-react';
import { api,useData,useMutation,Feedback,Modal,slugify,downloadJson,date } from './api';
import type { Field,Collection,Item,PanelProps } from './types';
const FIELD_TYPES=['TEXT','RICH_TEXT','NUMBER','BOOLEAN','DATE','EMAIL','URL','IMAGE','COLOR','OPTION','REFERENCE','MULTI_REFERENCE'];
function SchemaEditor({collection,collections,base,onDone,reload}:{collection:Collection|null;collections:Collection[];base:string;onDone:()=>void;reload:()=>void}){
  const [name,setName]=useState(collection?.name||''),[slug,setSlug]=useState(collection?.slug||''),[fields,setFields]=useState<Field[]>(collection?.fields||[]);
  const m=useMutation(reload);
  const edit=(i:number,change:Partial<Field>)=>setFields(previous=>previous.map((f,index)=>index===i?{...f,...change}:f));
  async function save(e:FormEvent){e.preventDefault();const result=await m.send(collection?`${base}/collections/${collection.id}`:`${base}/collections`,collection?'PUT':'POST',{name,slug,fields,...(collection?{revision:collection.revision}:{})},'Collection schema saved');if(result)onDone();}
  return <Modal title={collection?'Collection settings':'New collection'} onClose={onDone} busy={m.busy}><form onSubmit={save}><div className="sn-row"><label>Name<input required maxLength={120} value={name} onChange={e=>{setName(e.target.value);if(!collection)setSlug(slugify(e.target.value));}}/></label><label>Collection slug<input required pattern="[a-z0-9]+(-[a-z0-9]+)*" value={slug} onChange={e=>setSlug(e.target.value)}/></label></div><p className="sn-help">Name and slug are built in. Add typed fields below. Populated schemas cannot silently remove fields or change their types.</p>
    {fields.map((f,i)=><fieldset className="sn-field-card" key={i}><legend>Field {i+1}</legend><div className="sn-row"><label>Label<input value={f.name} required onChange={e=>edit(i,{name:e.target.value})}/></label><label>Key<input value={f.key} required pattern="[a-z][a-z0-9_]*" onChange={e=>edit(i,{key:e.target.value})}/></label><label>Type<select aria-label="Type" value={f.type} onChange={e=>edit(i,{type:e.target.value,options:e.target.value==='OPTION'?['Option 1']:undefined,referenceCollection:undefined})}>{FIELD_TYPES.map(t=><option key={t}>{t}</option>)}</select></label></div><div className="sn-row"><label className="sn-check"><input type="checkbox" checked={f.required} onChange={e=>edit(i,{required:e.target.checked})}/>Required when publishing</label><button type="button" className="sn-link" onClick={()=>setFields(fields.filter((_,index)=>index!==i))}><Trash2 size={14}/>Remove field</button></div>
      {f.type==='OPTION'&&<label>Options, one per line<textarea value={(f.options||[]).join('\n')} onChange={e=>edit(i,{options:e.target.value.split('\n')})}/></label>}
      {['REFERENCE','MULTI_REFERENCE'].includes(f.type)&&<label>Reference collection<select required value={f.referenceCollection||''} onChange={e=>edit(i,{referenceCollection:e.target.value})}><option value="">Choose collection</option>{collections.map(c=><option key={c.id} value={c.id}>{c.name}</option>)}</select></label>}
    </fieldset>)}<button type="button" className="sn-button" disabled={fields.length>=50} onClick={()=>setFields([...fields,{key:`field_${fields.length+1}`,name:'New field',type:'TEXT',required:false}])}><Plus size={15}/>Add field</button><Feedback state={m}/><footer><button className="sn-button" type="button" onClick={onDone} disabled={m.busy}>Cancel</button><button className="sn-button sn-primary" disabled={m.busy}>Save collection</button></footer></form></Modal>;
}
function ReferenceField({field,value,onChange,base}:{field:Field;value:any;onChange:(value:any)=>void;base:string}){
  const r=useData(field.referenceCollection?`${base}/collections/${field.referenceCollection}/options`:null);
  const multi=field.type==='MULTI_REFERENCE';
  return <label>{field.name}{field.required?' *':''}<select multiple={multi} value={value??(multi?[]:'')} onChange={e=>onChange(multi?Array.from(e.target.selectedOptions).map(o=>o.value):e.target.value||null)}><option value="" disabled={multi}>No reference</option>{r.data?.options.map((o:any)=><option key={o.id} value={o.id}>{o.name}</option>)}</select><Feedback state={r}/></label>;
}
function InputField({field,value,onChange,base}:{field:Field;value:any;onChange:(v:any)=>void;base:string}){
  if(['REFERENCE','MULTI_REFERENCE'].includes(field.type))return <ReferenceField field={field} value={value} onChange={onChange} base={base}/>;
  if(field.type==='BOOLEAN')return <label className="sn-check"><input type="checkbox" checked={value===true} onChange={e=>onChange(e.target.checked)}/>{field.name}{field.required?' *':''}</label>;
  return <label>{field.name}{field.required?' *':''}{field.type==='RICH_TEXT'?<><textarea rows={7} value={value||''} onChange={e=>onChange(e.target.value)}/><span className="sn-help">HTML is stored as content and sanitized when displayed in the public content viewer.</span></>:field.type==='OPTION'?<select value={value||''} onChange={e=>onChange(e.target.value)}><option value="">Choose</option>{field.options?.map(o=><option key={o}>{o}</option>)}</select>:<input type={field.type==='NUMBER'?'number':field.type==='DATE'?'date':field.type==='EMAIL'?'email':['URL','IMAGE'].includes(field.type)?'url':'text'} step={field.type==='NUMBER'?'any':undefined} value={value??''} placeholder={field.type==='COLOR'?'#112233':undefined} onChange={e=>onChange(field.type==='NUMBER'?(e.target.value===''?null:Number(e.target.value)):e.target.value)}/>}</label>;
}
function ItemEditor({item,collection,locale,groupId,base,onDone,reload}:{item:Item|null;collection:Collection;locale:string;groupId?:string;base:string;onDone:()=>void;reload:()=>void}){
  const [name,setName]=useState(item?.name||''),[slug,setSlug]=useState(item?.slug||''),[values,setValues]=useState<Record<string,any>>(item?.fields||{});const m=useMutation(reload);
  async function save(e:FormEvent){e.preventDefault();const result=await m.send(item&&!groupId?`${base}/items/${item.id}`:`${base}/collections/${collection.id}/items`,item&&!groupId?'PUT':'POST',{name,slug,fields:values,...(item&&!groupId?{revision:item.revision}:{locale,...(groupId?{groupId}:{})})},'Draft saved — live content was not changed');if(result)onDone();}
  return <Modal title={`${groupId?'New translation':item?'Edit item':'New item'} · ${locale}`} onClose={onDone} busy={m.busy}><form onSubmit={save}><p className="sn-help">Saving updates only the draft. Publish from the item list when the content is ready.</p><div className="sn-row"><label>Name<input required maxLength={200} value={name} onChange={e=>{setName(e.target.value);if(!item)setSlug(slugify(e.target.value));}}/></label><label>Slug<input required maxLength={160} pattern="[a-z0-9]+(-[a-z0-9]+)*" value={slug} onChange={e=>setSlug(e.target.value)}/></label></div><div className="sn-form-fields">{collection.fields.map(f=><InputField key={f.key} field={f} value={values[f.key]} onChange={v=>setValues(previous=>({...previous,[f.key]:v}))} base={base}/>)}</div><Feedback state={m}/><footer><button type="button" className="sn-button" onClick={onDone} disabled={m.busy}>Cancel</button><button className="sn-button sn-primary" disabled={m.busy}>Save draft</button></footer></form></Modal>;
}
function HistoryDialog({item,base,onDone,reload}:{item:Item;base:string;onDone:()=>void;reload:()=>void}){
  const r=useData(`${base}/items/${item.id}/revisions`);const m=useMutation(reload);
  return <Modal title={`Revision history · ${item.name}`} onClose={onDone} busy={m.busy}><p className="sn-help">Restoring creates a new draft revision. It never silently changes the published item.</p><Feedback state={r}/><Feedback state={m}/>{r.data?.revisions.map((v:any)=><article className="sn-history" key={v.id}><div><strong>Revision {v.revision} · {v.snapshot.name}</strong><small>{v.author||'Member'} · {date(v.createdAt)}</small></div><button className="sn-button" disabled={m.busy} onClick={async()=>{if(await m.send(`${base}/items/${item.id}/restore`,'POST',{revision:item.revision,targetRevision:v.revision},'Draft restored'))onDone();}}>Restore as draft</button></article>)}</Modal>;
}
export default function CmsPanel({site,collections,locales,refresh,reload}:PanelProps&{collections:Collection[]}){
  const base=`/sites/${site.id}`;const [collectionId,setCollectionId]=useState(collections[0]?.id||''),[locale,setLocale]=useState('en'),[q,setQ]=useState(''),[offset,setOffset]=useState(0);
  const collection=collections.find(c=>c.id===collectionId)||collections[0];const canEdit=site.capabilities.includes('EDIT_CONTENT'),canSchema=site.capabilities.includes('EDIT_DESIGN'),canPublish=site.capabilities.includes('PUBLISH');
  const r=useData(collection?`${base}/collections/${collection.id}/items?locale=${encodeURIComponent(locale)}&q=${encodeURIComponent(q)}&offset=${offset}`:null,refresh);const m=useMutation(reload);
  const [schema,setSchema]=useState<Collection|null|undefined>(undefined),[editor,setEditor]=useState<{item:Item|null;locale:string;groupId?:string}|null>(null),[history,setHistory]=useState<Item|null>(null),[schedule,setSchedule]=useState<Item|null>(null),[when,setWhen]=useState('');
  async function action(item:Item,action:string){if(['ARCHIVE','UNPUBLISH'].includes(action)&&!window.confirm(`${action==='ARCHIVE'?'Archive and unpublish':'Unpublish'} ${item.name}? The draft will be kept.`))return;await m.send(`${base}/items/${item.id}/actions`,'POST',{revision:item.revision,action},`Item ${action.toLowerCase().replaceAll('_',' ')}`);}
  async function importFile(file:File|undefined){if(!file||!collection)return;if(file.size>1_000_000){m.setError('Import files must be below 1 MB.');return;}try{const parsed=JSON.parse(await file.text());await m.send(`${base}/collections/${collection.id}/import`,'POST',{items:Array.isArray(parsed)?parsed:parsed.items},'Items imported as drafts');}catch(e){m.setError(e instanceof Error?e.message:'Invalid import JSON');}}
  return <section><div className="sn-section-heading"><div><h2>CMS collections</h2><p>Typed content, versioned drafts, references, and independent locale variants.</p></div>{canSchema&&<button className="sn-button sn-primary" onClick={()=>setSchema(null)}><Plus size={15}/>New collection</button>}</div>
    <div className="sn-toolbar"><label>Collection<select value={collection?.id||''} onChange={e=>{setCollectionId(e.target.value);setOffset(0);}}><option value="" disabled>Select a collection</option>{collections.map(c=><option key={c.id} value={c.id}>{c.name} ({c.itemCount})</option>)}</select></label><label>Locale<select value={locale} onChange={e=>{setLocale(e.target.value);setOffset(0);}}>{locales.map(l=><option key={l.code} value={l.code}>{l.name}{l.enabled?'':' · disabled publicly'}</option>)}</select></label><label>Search items<input value={q} onChange={e=>{setQ(e.target.value);setOffset(0);}}/></label>{collection&&canSchema&&<button className="sn-button" onClick={()=>setSchema(collection)}><Settings size={15}/>Schema</button>}{collection&&canEdit&&<button className="sn-button sn-primary" onClick={()=>setEditor({item:null,locale})}><Plus size={15}/>New item</button>}</div>
    <Feedback state={m}/><Feedback state={r}/>{!collection&&<div className="sn-empty"><h3>Create your first collection</h3><p>Build a schema for articles, projects, properties, or any structured content.</p></div>}
    {collection&&<><div className="sn-row sn-actions"><Link to={`/content/${site.id}/${collection.slug}?locale=${locale}`} target="_blank" rel="noreferrer" className="sn-button">Open published collection</Link><button className="sn-button" disabled={!r.data?.items.length} onClick={()=>downloadJson(`${collection.slug}-${locale}-page.json`,{items:r.data!.items.map((i:Item)=>({name:i.name,slug:i.slug,fields:i.fields,locale:i.locale}))})}><Download size={14}/>Export this page</button>{canEdit&&<label className="sn-upload"><Upload size={14}/>Import JSON<input type="file" accept="application/json,.json" disabled={m.busy} onChange={e=>{void importFile(e.target.files?.[0]);e.target.value='';}}/></label>}</div><p className="sn-help">Public content is visible only after both the item and its site are published. JSON import accepts up to 100 drafts per transaction. Export includes the currently loaded page.</p>
    {r.data&&<div className="sn-table"><table><thead><tr><th>Name</th><th>State</th><th>Revision</th><th>Actions</th></tr></thead><tbody>{r.data.items.map((i:Item)=><tr key={i.id}><td><button className="sn-text-button" onClick={()=>canEdit&&setEditor({item:i,locale:i.locale})}>{i.name}</button><small>/{i.slug}</small></td><td><span className={`sn-badge ${i.isLive?'sn-green':''}`}>{i.archived?'Archived':i.scheduledAt?'Scheduled':i.isLive?(i.liveRevision===i.revision?'Published':'Published · draft changes'):i.ready?'Ready for review':'Draft'}</span>{i.scheduledAt&&<small>{date(i.scheduledAt)}</small>}</td><td>{i.revision}</td><td><div className="sn-inline-actions"><button title="Revision history" className="sn-button" onClick={()=>setHistory(i)}><History size={14}/></button>{canEdit&&<button className="sn-button" disabled={m.busy} onClick={()=>{void action(i,i.archived?'RESTORE':'READY');}}>{i.archived?'Restore':'Mark ready'}</button>}{canPublish&&!i.archived&&<><button className="sn-button" disabled={m.busy} onClick={()=>{void action(i,'PUBLISH');}}>Publish</button><button className="sn-button" disabled={m.busy} onClick={()=>{setSchedule(i);setWhen('');}}>Schedule</button>{i.scheduledAt&&<button className="sn-button" disabled={m.busy} onClick={()=>{void action(i,'CANCEL_SCHEDULE');}}>Cancel schedule</button>}{i.isLive&&<button className="sn-button" disabled={m.busy} onClick={()=>{void action(i,'UNPUBLISH');}}>Unpublish</button>}<button className="sn-button" disabled={m.busy} onClick={()=>{void action(i,'ARCHIVE');}}>Archive</button></>}{canEdit&&locales.length>1&&<select aria-label={`Translate ${i.name}`} value="" onChange={e=>{if(e.target.value)setEditor({item:i,locale:e.target.value,groupId:i.groupId});}}><option value="">Add translation</option>{locales.filter(l=>l.code!==i.locale).map(l=><option key={l.code} value={l.code}>{l.name}</option>)}</select>}</div></td></tr>)}</tbody></table>{!r.data.items.length&&<p className="sn-empty">No items in this locale or search.</p>}</div>}
    {r.data&&<div className="sn-pagination"><span>{r.data.total} items · {offset+1}–{Math.min(offset+25,r.data.total)}</span><button className="sn-button" disabled={!offset} onClick={()=>setOffset(Math.max(0,offset-25))}>Previous</button><button className="sn-button" disabled={offset+25>=r.data.total} onClick={()=>setOffset(offset+25)}>Next</button></div>}</>}
    {schema!==undefined&&<SchemaEditor collection={schema} collections={collections} base={base} onDone={()=>setSchema(undefined)} reload={reload}/>}
    {editor&&collection&&<ItemEditor item={editor.item} collection={collection} locale={editor.locale} groupId={editor.groupId} base={base} onDone={()=>setEditor(null)} reload={reload}/>}
    {history&&<HistoryDialog item={history} base={base} onDone={()=>setHistory(null)} reload={reload}/>}
    {schedule&&<Modal title={`Schedule · ${schedule.name}`} onClose={()=>setSchedule(null)} busy={m.busy}><p>Publish this saved revision at the selected time. Editing the draft cancels its schedule. The Studio worker must be running.</p><label>Publish at (your local time)<input type="datetime-local" value={when} onChange={e=>setWhen(e.target.value)}/></label><Feedback state={m}/><button className="sn-button sn-primary" disabled={m.busy||!when} onClick={async()=>{const time=new Date(when);if(Number.isNaN(time.valueOf())){m.setError('Choose a valid date');return;}if(await m.send(`${base}/items/${schedule.id}/actions`,'POST',{action:'SCHEDULE',revision:schedule.revision,scheduledAt:time.toISOString()},'Publication scheduled'))setSchedule(null);}}>Schedule publication</button></Modal>}
  </section>;
}
