import { useState } from 'react';
import { Link } from 'react-router-dom';
import { Plus,ExternalLink } from 'lucide-react';
import { useData,useMutation,Feedback,Modal,date } from './api';
import type { PanelProps } from './types';
function ProductEditor({product,base,onClose,reload}:{product?:any;base:string;onClose:()=>void;reload:()=>void}){
  const [form,setForm]=useState({name:product?.name||'',description:product?.description||'',priceMinor:product?.priceMinor||100,currency:product?.currency||'usd',stripePriceId:product?.stripePriceId||'',active:product?.active||false});
  const m=useMutation(reload);
  return <Modal title={product?'Edit product':'New product'} busy={m.busy} onClose={onClose}><form onSubmit={async e=>{e.preventDefault();const result=await m.send(`${base}/products${product?`/${product.id}`:''}`,product?'PUT':'POST',{...form,...(product?{revision:product.revision}:{})},'Product saved');if(result)onClose();}}><label>Name<input required maxLength={120} value={form.name} onChange={e=>setForm({...form,name:e.target.value})}/></label><label>Description<textarea maxLength={10000} value={form.description} onChange={e=>setForm({...form,description:e.target.value})}/></label><div className="sn-two-columns"><label>Price in minor units<input type="number" min={1} max={100000000} step={1} required value={form.priceMinor} onChange={e=>setForm({...form,priceMinor:Number(e.target.value)})}/></label><label>Currency<select value={form.currency} onChange={e=>setForm({...form,currency:e.target.value})}>{['usd','eur','gbp','inr'].map(c=><option key={c}>{c}</option>)}</select></label></div><p className="sn-help">For these currencies, 100 minor units = 1.00. Checkout verifies this price against Stripe; the browser never supplies the charged amount.</p><label>Existing Stripe one-time price ID<input required pattern="price_[a-zA-Z0-9]+" value={form.stripePriceId} onChange={e=>setForm({...form,stripePriceId:e.target.value})} placeholder="price_…"/></label><label className="sn-check"><input type="checkbox" checked={form.active} onChange={e=>setForm({...form,active:e.target.checked})}/>Show in published catalog</label><Feedback state={m}/><footer><button type="button" className="sn-button" onClick={onClose} disabled={m.busy}>Cancel</button><button className="sn-button sn-primary" disabled={m.busy}>Save product</button></footer></form></Modal>;
}
export default function CommercePanel({site,refresh,reload}:PanelProps){
  const base=`/sites/${site.id}`,r=useData(`${base}/products`,refresh),[editor,setEditor]=useState<any>(undefined);
  return <section><div className="sn-section-heading"><div><h2>Products & checkout</h2><p>One-product hosted checkout with server-verified prices and signed payment webhooks.</p></div><div className="sn-inline-actions"><Link className="sn-button" to={`/shop/${site.id}`} target="_blank" rel="noopener noreferrer"><ExternalLink size={15}/>Public catalog</Link><button className="sn-button sn-primary" onClick={()=>setEditor(null)}><Plus size={15}/>New product</button></div></div><Feedback state={r}/>{r.data&&<><p className={r.data.checkoutConfigured?'sn-notice':'sn-warning'}>{r.data.checkoutConfigured?'Payment-provider configuration is present. Verify the complete checkout in your Stripe test environment before accepting live payments.':'Checkout is disabled. Configure a Stripe key, signed webhook secret, approved site/account mapping, and frontend origin on the server.'}</p><p className="sn-help">This checkout does not implement inventory, taxes, shipping, refunds, or recurring subscription billing. Returning from Stripe is not proof of payment: only a matching signed webhook marks an order paid.</p><div className="sn-table"><table><thead><tr><th>Product</th><th>Price</th><th>Visibility</th><th>Actions</th></tr></thead><tbody>{r.data.products.map((p:any)=><tr key={p.id}><td><strong>{p.name}</strong><small>{p.stripePriceId}</small></td><td>{(p.priceMinor/100).toFixed(2)} {p.currency.toUpperCase()}</td><td><span className="sn-badge">{p.active?'Active':'Hidden'}</span></td><td><button className="sn-button" onClick={()=>setEditor(p)}>Edit product</button></td></tr>)}</tbody></table>{!r.data.products.length&&<p className="sn-empty">No products yet.</p>}</div><h3 className="sn-subheading">Recent orders</h3><div className="sn-table"><table><thead><tr><th>Order / product</th><th>Total</th><th>Status</th><th>Created</th></tr></thead><tbody>{r.data.orders.map((o:any)=><tr key={o.id}><td>{o.name}<small>{o.id} · Quantity {o.quantity}</small></td><td>{(o.totalMinor/100).toFixed(2)} {o.currency.toUpperCase()}</td><td><span className="sn-badge">{o.state}</span></td><td>{date(o.createdAt)}</td></tr>)}</tbody></table>{!r.data.orders.length&&<p className="sn-empty">No checkout orders recorded.</p>}</div></>}{editor!==undefined&&<ProductEditor product={editor||undefined} base={base} onClose={()=>setEditor(undefined)} reload={reload}/>}</section>;
}
