import {useState,type FormEvent} from 'react';
import {useData,useMutation,Feedback} from './api';
import type {PanelProps} from './types';

export default function PersonalizationPanel({site,refresh,reload}:PanelProps){
  const base=`/sites/${site.id}/personalization`,state=useData(base,refresh),m=useMutation(reload);
  const [name,setName]=useState('Campaign hero'),[target,setTarget]=useState('heading'),[path,setPath]=useState('/'),[campaign,setCampaign]=useState(''),[device,setDevice]=useState(''),[text,setText]=useState('Personalized headline'),[priority,setPriority]=useState(100);
  async function create(e:FormEvent){e.preventDefault();const conditions:any[]=[{attribute:'path',operator:'PREFIX',value:path}];if(campaign)conditions.push({attribute:'utmCampaign',operator:'EQ',value:campaign});if(device)conditions.push({attribute:'deviceCategory',operator:'EQ',value:device});await m.send(base,'POST',{name,priority,conditions,targetElementId:target,variant:{text}},'Personalization rule created');}
  async function change(rule:any,next:string){await m.send(`${base}/${rule.id}/state`,'PATCH',{state:next,revision:rule.revision},`Rule ${next.toLowerCase()}`);}
  async function remove(rule:any){if(!window.confirm(`Delete ${rule.name}?`))return;await m.send(`${base}/${rule.id}`,'DELETE',undefined,'Rule deleted');}
  return <section><div className="sn-section-heading"><div><h2>Personalization</h2><p>Deterministic targeting only. Rules alter presentation and never participate in permissions, billing or ownership decisions.</p></div></div>
    <Feedback state={state}/><Feedback state={m}/>
    {site.capabilities.includes('MANAGE_SETTINGS')&&<form className="sn-card" onSubmit={create}><h3>New rule</h3><div className="sn-row"><label>Name<input required maxLength={120} value={name} onChange={e=>setName(e.target.value)}/></label><label>Target element ID<input required maxLength={150} value={target} onChange={e=>setTarget(e.target.value)}/></label><label>Priority<input type="number" min={0} max={100000} value={priority} onChange={e=>setPriority(Number(e.target.value))}/></label></div><div className="sn-row"><label>Path prefix<input required value={path} onChange={e=>setPath(e.target.value)}/></label><label>UTM campaign<input value={campaign} maxLength={120} onChange={e=>setCampaign(e.target.value)} placeholder="Optional"/></label><label>Device<select value={device} onChange={e=>setDevice(e.target.value)}><option value="">Any device</option><option value="desktop">Desktop</option><option value="tablet">Tablet</option><option value="mobile">Mobile</option></select></label></div><label>Replacement text<textarea maxLength={5000} value={text} onChange={e=>setText(e.target.value)}/></label><button className="sn-button sn-primary" disabled={m.busy}>Create draft rule</button></form>}
    <div className="sn-card"><div className="sn-panel-head"><div><h3>Rules</h3><p className="sn-help">Lower priority numbers run first. Only the first matching running rule for each target element is returned.</p></div><span className={`sn-badge ${state.data?.enabled?'sn-green':''}`}>{state.data?.enabled?'Feature enabled':'Feature disabled'}</span></div>
      {state.data?.rules?.length?<div className="sn-table"><table><thead><tr><th>Name</th><th>Target</th><th>Priority</th><th>State</th><th>Actions</th></tr></thead><tbody>{state.data.rules.map((rule:any)=><tr key={rule.id}><td>{rule.name}<small>{rule.conditions?.map((c:any)=>`${c.attribute} ${c.operator} ${String(c.value)}`).join(' · ')}</small></td><td>{rule.targetElementId}</td><td>{rule.priority}</td><td><span className="sn-badge">{rule.state}</span></td><td><div className="sn-inline-actions">{rule.state!=='RUNNING'&&<button className="sn-button" disabled={m.busy||!state.data.enabled} onClick={()=>void change(rule,'RUNNING')}>Run</button>}{rule.state==='RUNNING'&&<button className="sn-button" disabled={m.busy} onClick={()=>void change(rule,'PAUSED')}>Pause</button>}{rule.state!=='RUNNING'&&<button className="sn-button" disabled={m.busy} onClick={()=>void remove(rule)}>Delete</button>}</div></td></tr>)}</tbody></table></div>:<p className="sn-empty">No personalization rules yet.</p>}
    </div>
  </section>;
}