import { useEffect,useState } from 'react';
import { useAuth } from '../../context/AuthContext';
import { useCanvasPresence } from '../collaboration/hooks/useCanvasPresence';
import { useData,useMutation,Feedback,date } from './api';
import type { PanelProps } from './types';
export default function ReviewPanel({site,refresh,reload}:PanelProps){
  const {user}=useAuth();const [poll,setPoll]=useState(0),[content,setContent]=useState(''),[elementId,setElementId]=useState(''),[reply,setReply]=useState<Record<string,string>>({});const base=`/sites/${site.id}`;
  const r=useData(`${base}/threads`,refresh+poll),m=useMutation(reload);
  const {peers,isConnected}=useCanvasPresence(site.id,user?{id:user.id,name:user.fullName||'Member'}:null);
  useEffect(()=>{const timer=setInterval(()=>{if(document.visibilityState==='visible')setPoll(v=>v+1);},15000);return()=>clearInterval(timer);},[]);
  const canComment=site.capabilities.includes('COMMENT');
  return <section><div className="sn-section-heading"><div><h2>Review & collaboration</h2><p>Threaded feedback and authenticated live presence. Conflicting document saves require reconciliation rather than silently replacing another editor’s work.</p></div><span className={`sn-badge ${isConnected?'sn-green':''}`}>{isConnected?'Presence connected':'Presence disconnected'}</span></div><div className="sn-peers">{peers.map(p=><span key={p.socketId} className="sn-peer"><i style={{background:p.user.color}}/>{p.user.name}</span>)}{!peers.length&&<span>No other collaborators are currently visible.</span>}</div><Feedback state={r}/><Feedback state={m}/>{canComment&&<form className="sn-card" onSubmit={async e=>{e.preventDefault();if(await m.send(`${base}/threads`,'POST',{content,...(elementId?{elementId}:{})},'Review thread created')){setContent('');setElementId('');}}}><label>New review comment<textarea required maxLength={4000} value={content} onChange={e=>setContent(e.target.value)} placeholder="What needs attention?"/></label><div className="sn-row"><label>Element ID (optional)<input value={elementId} maxLength={150} onChange={e=>setElementId(e.target.value)}/></label><button className="sn-button sn-primary" disabled={m.busy}>Post comment</button></div></form>}
    {r.data?.threads.map((t:any)=><article className="sn-thread" key={t.id}><header><div><strong>{t.author||'Collaborator'}</strong><small>{date(t.createdAt)}{t.elementId?` · Element: ${t.elementId}`:''}</small></div><span className={`sn-badge ${t.resolved?'sn-green':''}`}>{t.resolved?'Resolved':'Open'}</span></header><p>{t.content}</p>{t.replies.map((reply:any)=><blockquote key={reply.id}><strong>{reply.author||'Collaborator'}</strong><small>{date(reply.createdAt)}</small><p>{reply.content}</p></blockquote>)}{canComment&&<><form className="sn-row" onSubmit={async e=>{e.preventDefault();if(await m.send(`${base}/threads/${t.id}`,'PATCH',{content:reply[t.id]||''},'Reply posted'))setReply({...reply,[t.id]:''});}}><label className="sn-grow">Reply<input required maxLength={4000} value={reply[t.id]||''} onChange={e=>setReply({...reply,[t.id]:e.target.value})}/></label><button className="sn-button" disabled={m.busy}>Reply</button></form><button className="sn-link" disabled={m.busy} onClick={()=>{void m.send(`${base}/threads/${t.id}`,'PATCH',{resolved:!t.resolved,revision:t.revision},t.resolved?'Thread reopened':'Thread resolved');}}>{t.resolved?'Reopen':'Resolve'} thread</button></>}</article>)}{r.data?.threads.length===0&&<div className="sn-empty">No review threads yet.</div>}
  </section>;
}
