import { lazy,Suspense,useState,useEffect } from 'react';
import { Link,useParams,useSearchParams } from 'react-router-dom';
import { ArrowLeft,ArrowUpRight,RefreshCw } from 'lucide-react';
import { useData,Feedback } from './api';
import type { PanelProps } from './types';
import './studio-next.css';
const panels={collections:lazy(()=>import('./CmsPanel')),localization:lazy(()=>import('./LocalesPanel')),reviews:lazy(()=>import('./ReviewPanel')),snapshots:lazy(()=>import('./SnapshotsPanel')),permissions:lazy(()=>import('./PermissionsPanel')),domains:lazy(()=>import('./DomainsPanel')),commerce:lazy(()=>import('./CommercePanel')),analytics:lazy(()=>import('./AnalyticsPanel')),ai:lazy(()=>import('./AiPanel')),releases:lazy(()=>import('./ReleasesPanel')),webhooks:lazy(()=>import('./WebhooksPanel')),governance:lazy(()=>import('./GovernancePanel')),agent:lazy(()=>import('./AgentPanel')),blog:lazy(()=>import('./BlogPanel')),personalization:lazy(()=>import('./PersonalizationPanel'))};
const names={collections:'Collections',localization:'Localization',reviews:'Reviews',snapshots:'Snapshots',permissions:'Permissions',domains:'Domains',commerce:'Commerce',analytics:'Analytics',ai:'AI Assistant',releases:'Releases',webhooks:'Webhooks',governance:'Governance',agent:'Agent API',blog:'Blog',personalization:'Personalization'};
export default function SiteStudio(){
  const {siteId}=useParams(),[params,setParams]=useSearchParams(),[refresh,setRefresh]=useState(0);const reload=()=>setRefresh(v=>v+1);
  const r=useData(`/sites/${siteId}/collections`,refresh);const chosen=params.get('panel')||'collections',tab=Object.hasOwn(panels,chosen)?chosen as keyof typeof panels:'collections',Panel=panels[tab];
  const [previous,setPrevious]=useState<{id:string|undefined;data:any}>({id:undefined,data:null});
  useEffect(()=>{if(r.data)setPrevious({id:siteId,data:r.data});},[r.data,siteId]);
  const data=r.data||(!r.error&&previous.id===siteId?previous.data:null);
  const site=data?.site;const props:PanelProps={site,locales:data?.locales||[],collections:data?.collections||[],refresh,reload};
  return <div className="sn"><header className="sn-header"><Link className="sn-back" to="/dashboard"><ArrowLeft size={17}/>Dashboard</Link><Link className="sn-wordmark" to="/dashboard">ForgeStudio <span>Site Studio</span></Link><div className="sn-inline-actions"><button className="sn-button" aria-label="Reload site tools" onClick={reload}><RefreshCw size={15}/></button><Link className="sn-button sn-primary" to={`/editor/${siteId}`}>Open Designer<ArrowUpRight size={15}/></Link></div></header><main className="sn-main"><div className="sn-title"><p className="sn-eyebrow">CONTENT · COLLABORATION · DELIVERY</p><h1>{site?.name||'Site Studio'}</h1><p>Manage content and its published state, with permission checks on every operation.</p></div><Feedback state={r}/>{site&&<><nav className="sn-tabs" aria-label="Site tools">{Object.entries(names).filter(([key])=>!['domains','commerce','permissions','webhooks','governance'].includes(key)||site.capabilities.includes('MANAGE_SETTINGS')).filter(([key])=>!['analytics','personalization'].includes(key)||site.capabilities.includes('VIEW_ANALYTICS')).filter(([key])=>key!=='ai'||site.capabilities.includes('EDIT_CONTENT')).filter(([key])=>key!=='releases'||site.capabilities.includes('PUBLISH')).map(([key,name])=><button key={key} aria-current={tab===key?'page':undefined} onClick={()=>setParams({panel:key})}>{name}</button>)}</nav><Suspense fallback={<p role="status">Loading site tools…</p>}><Panel key={`${siteId}:${tab}`} {...props}/></Suspense></>}<footer className="sn-footer">ForgeStudio · Site tools are separate from live hosting. Publishing content does not provision infrastructure.</footer></main></div>;
}
