import {useEffect,useState} from "react";
import {Cpu,RefreshCw,ShieldCheck,AlertTriangle,CheckCircle2} from "lucide-react";

type Provider={provider:string;credentialConfigured:boolean;approvedModels:string[];health:string};
type Route={feature:string;provider:string;model:string;fallbackModels:string[];enabled:boolean;timeoutMs:number;maxOutputTokens:number;source:string};
type Infra={providers:Provider[];routes:(Route|null)[];usage24h:any[];features:string[]};
export default function AiInfrastructurePanel({apiUrl}:{apiUrl:string}){
  const [data,setData]=useState<Infra|null>(null),[loading,setLoading]=useState(false),[busy,setBusy]=useState<string|null>(null),[message,setMessage]=useState<{type:"success"|"error";text:string}|null>(null);
  async function load(){setLoading(true);setMessage(null);try{const r=await fetch(`${apiUrl}/api/v1/operations/admin/ai-infrastructure`,{credentials:"include"});const v=await r.json();if(!r.ok)throw new Error(v?.error?.message||"Unable to load AI infrastructure");setData(v.data);}catch(e:any){setMessage({type:"error",text:e?.message||"Unable to load AI infrastructure"});}finally{setLoading(false);}}
  useEffect(()=>{void load();},[]);
  async function check(provider:string){setBusy("provider:"+provider);try{const r=await fetch(`${apiUrl}/api/v1/operations/admin/ai-infrastructure/providers/${provider}/check`,{method:"POST",credentials:"include"});const v=await r.json();if(!r.ok)throw new Error(v?.error?.message||"Health check failed");setData(prev=>prev?{...prev,providers:prev.providers.map(p=>p.provider===provider?{...p,health:v.data.status}:p)}:prev);setMessage({type:"success",text:`${provider} health: ${v.data.status}${v.data.latencyMs!=null?` · ${v.data.latencyMs}ms`:""}`});}catch(e:any){setMessage({type:"error",text:e?.message||"Health check failed"});}finally{setBusy(null);}}
  async function save(route:Route){setBusy("route:"+route.feature);try{const r=await fetch(`${apiUrl}/api/v1/operations/admin/ai-infrastructure/routes/${route.feature}`,{method:"PUT",credentials:"include",headers:{"Content-Type":"application/json"},body:JSON.stringify({provider:route.provider,model:route.model,fallbackModels:route.fallbackModels,enabled:route.enabled,timeoutMs:route.timeoutMs,maxOutputTokens:route.maxOutputTokens})});const v=await r.json();if(!r.ok)throw new Error(v?.error?.message||"Route update failed");setMessage({type:"success",text:`${route.feature} route saved`});await load();}catch(e:any){setMessage({type:"error",text:e?.message||"Route update failed"});}finally{setBusy(null);}}
  function update(feature:string,patch:Partial<Route>){setData(prev=>prev?{...prev,routes:prev.routes.map(r=>r?.feature===feature?{...r,...patch}:r)}:prev);}
  const routes=(data?.routes||[]).filter(Boolean) as Route[];
  return <div className="space-y-6">
    <div className="flex items-center justify-between gap-4"><div><h2 className="text-lg font-bold text-white">AI Infrastructure</h2><p className="text-xs text-slate-400">Approved providers, model routing, fallbacks, limits and recent usage. Secret values are never displayed.</p></div><button onClick={()=>void load()} disabled={loading} className="px-3 py-2 rounded-lg bg-slate-800 border border-slate-700 text-xs font-bold"><RefreshCw className={`w-4 h-4 inline mr-2 ${loading?"animate-spin":""}`}/>Refresh</button></div>
    {message&&<div className={`rounded-xl border p-3 text-sm ${message.type==="success"?"border-emerald-800 bg-emerald-950/40 text-emerald-300":"border-red-800 bg-red-950/40 text-red-300"}`}>{message.text}</div>}
    <section className="grid md:grid-cols-2 gap-4">{data?.providers.map(p=><div key={p.provider} className="rounded-2xl border border-slate-800 bg-slate-900/60 p-5 space-y-3"><div className="flex items-center justify-between"><div className="flex items-center gap-2"><Cpu className="w-4 h-4 text-amber-400"/><h3 className="font-bold capitalize">{p.provider}</h3></div><span className={`text-[10px] font-bold px-2 py-1 rounded-full ${p.credentialConfigured?"bg-emerald-500/10 text-emerald-400":"bg-slate-800 text-slate-400"}`}>{p.credentialConfigured?"credential configured":"credential missing"}</span></div><div className="text-xs text-slate-400 flex items-center gap-2">{p.health==="HEALTHY"?<CheckCircle2 className="w-4 h-4 text-emerald-400"/>:<AlertTriangle className="w-4 h-4 text-amber-400"/>}<span>{p.health}</span></div><p className="text-[11px] text-slate-500">{p.approvedModels.length?p.approvedModels.join(", "):"No deployment-approved models configured."}</p><button disabled={busy==="provider:"+p.provider||!p.credentialConfigured} onClick={()=>void check(p.provider)} className="px-3 py-1.5 rounded-lg bg-slate-800 border border-slate-700 text-xs font-bold disabled:opacity-40">Run health check</button></div>)}</section>
    <section className="rounded-2xl border border-slate-800 bg-slate-900/60 overflow-hidden"><div className="p-5 border-b border-slate-800"><h3 className="font-bold">Model routing</h3><p className="text-xs text-slate-400">Only models from the deployment-approved registry can be persisted.</p></div><div className="overflow-x-auto"><table className="w-full text-xs"><thead className="bg-slate-950/60 text-slate-400"><tr><th className="p-3 text-left">Role</th><th className="p-3">Provider</th><th className="p-3">Model</th><th className="p-3">Timeout</th><th className="p-3">Max output</th><th className="p-3">Enabled</th><th className="p-3"></th></tr></thead><tbody className="divide-y divide-slate-800">{routes.map(route=>{const provider=data?.providers.find(p=>p.provider===route.provider);return <tr key={route.feature}><td className="p-3 font-bold text-amber-400">{route.feature}</td><td className="p-3"><select value={route.provider} onChange={e=>{const next=e.target.value;const first=data?.providers.find(p=>p.provider===next)?.approvedModels[0]||"";update(route.feature,{provider:next,model:first});}} className="bg-slate-950 border border-slate-700 rounded px-2 py-1"><option value="openai">OpenAI</option><option value="anthropic">Anthropic</option></select></td><td className="p-3"><select value={route.model} onChange={e=>update(route.feature,{model:e.target.value})} className="bg-slate-950 border border-slate-700 rounded px-2 py-1 max-w-48">{provider?.approvedModels.map(m=><option key={m} value={m}>{m}</option>)}</select></td><td className="p-3"><input type="number" min={1000} max={180000} value={route.timeoutMs} onChange={e=>update(route.feature,{timeoutMs:Number(e.target.value)})} className="w-24 bg-slate-950 border border-slate-700 rounded px-2 py-1"/></td><td className="p-3"><input type="number" min={128} max={64000} value={route.maxOutputTokens} onChange={e=>update(route.feature,{maxOutputTokens:Number(e.target.value)})} className="w-24 bg-slate-950 border border-slate-700 rounded px-2 py-1"/></td><td className="p-3 text-center"><input type="checkbox" checked={route.enabled} onChange={e=>update(route.feature,{enabled:e.target.checked})}/></td><td className="p-3"><button onClick={()=>void save(route)} disabled={busy==="route:"+route.feature||!route.model} className="px-3 py-1.5 rounded-lg bg-amber-500 text-slate-950 font-bold disabled:opacity-40">Save</button></td></tr>})}</tbody></table></div></section>
    <section className="rounded-2xl border border-slate-800 bg-slate-900/60 p-5"><div className="flex items-center gap-2 mb-3"><ShieldCheck className="w-4 h-4 text-emerald-400"/><h3 className="font-bold">24-hour AI usage</h3></div>{data?.usage24h?.length?<div className="overflow-x-auto"><table className="w-full text-xs"><thead className="text-slate-400"><tr><th className="text-left p-2">Provider</th><th className="text-left p-2">Model</th><th className="p-2">Requests</th><th className="p-2">Units</th><th className="p-2">Avg latency</th><th className="p-2">Success/Fail</th></tr></thead><tbody>{data.usage24h.map((u:any,i:number)=><tr key={i} className="border-t border-slate-800"><td className="p-2">{u.provider}</td><td className="p-2">{u.model}</td><td className="p-2 text-center">{u.requests}</td><td className="p-2 text-center">{u.units}</td><td className="p-2 text-center">{u.avgLatencyMs}ms</td><td className="p-2 text-center">{u.succeeded}/{u.failed}</td></tr>)}</tbody></table></div>:<p className="text-xs text-slate-500">No AI runs recorded in the past 24 hours.</p>}</section>
  </div>;
}
