import express,{type Request,type Response,type NextFunction,type RequestHandler} from 'express';
import { rateLimit } from 'express-rate-limit';
import { Database,type Actor } from './database.js';
import { Workspaces } from './workspaces.js';
import { Cms } from './cms.js';
import { CmsCommands } from './cms-commands.js';
import { Design } from './design.js';
import { Localization } from './localization.js';
import { Collaboration } from './collaboration.js';
import { Domains,type TxtResolver } from './domains.js';
import type {DomainProvider} from './domain-provider.js';
import { Analytics } from './analytics.js';
import { Commerce,stripeTransport,type CommerceConfig } from './commerce.js';
import { Permissions } from './permissions.js';
import { Releases } from './releases.js';
import { Webhooks,configuredWebhookConfig,type WebhookConfig } from './webhooks.js';
import { FeaturePolicy,AiGovernance } from './governance.js';
import { DomainCommands } from './commands.js';
import { AiOrchestrator,databaseConfiguredProvider,type AIProvider } from './ai.js';
import { AiSeo } from './ai-seo.js';
import { AgentTools } from './agent-tools.js';
import { Assets,type ImageGenerationProvider } from './assets.js';
import { CodeComponents,configuredCodeSandboxProvider,type CodeSandboxProvider } from './code-components.js';
import { observeStudioRequests } from './observability.js';
import { EnterpriseIdentity,type OidcTransport,type SecretResolver } from './enterprise.js';
import { configuredExternalPublishingProvider } from './cloud-publishing.js';
import { Blog } from './blog.js';
import { Personalization } from './personalization.js';
import { Quality,type VisualValidationProvider } from './quality.js';
import { StudioError,parse,localeCode } from './validation.js';
import { trustedOrigin } from '../studio/domain.js';
import { AUTH_COOKIE_NAME,AUTH_COOKIE_OPTIONS } from '../../config/auth.js';
export interface RouterOptions { commerce?:CommerceConfig;analyticsSecret?:string;resolveTxt?:TxtResolver;requestLimit?:number;aiProvider?:AIProvider|null;imageProvider?:ImageGenerationProvider|null;codeSandbox?:CodeSandboxProvider|null;visualValidation?:VisualValidationProvider|null;webhooks?:WebhookConfig;oidcTransport?:OidcTransport;oidcSecretResolver?:SecretResolver;domainProvider?:DomainProvider|null }
export function configuredCommerce():CommerceConfig{
  let accounts:Record<string,string>={};
  if(process.env.STUDIO_STRIPE_ACCOUNTS){
    try{const parsed=JSON.parse(process.env.STUDIO_STRIPE_ACCOUNTS);if(!parsed||typeof parsed!=='object'||Array.isArray(parsed)||Object.values(parsed).some(v=>typeof v!=='string'||!(v==='platform'||/^acct_[a-zA-Z0-9]+$/.test(v))))throw new Error();accounts=parsed;}catch{throw new Error('STUDIO_STRIPE_ACCOUNTS must map site UUIDs to approved Stripe account IDs or platform');}
  }
  return {accounts,origin:process.env.FRONTEND_URL?new URL(process.env.FRONTEND_URL).origin:'',webhookSecret:process.env.STUDIO_STRIPE_WEBHOOK_SECRET,...(process.env.STUDIO_STRIPE_SECRET?{transport:stripeTransport(process.env.STUDIO_STRIPE_SECRET)}:{})};
}
export function createStudioNextRouter(db:Database,options:RouterOptions={}){
  const router=express.Router();
  const commands=new DomainCommands(db),workspaces=new Workspaces(db),featurePolicy=new FeaturePolicy(db),aiGovernance=new AiGovernance(db),webhooks=new Webhooks(db,options.webhooks??configuredWebhookConfig()),cms=new Cms(db,webhooks),cmsCommands=new CmsCommands(db,cms),design=new Design(db,commands),localization=new Localization(db),reviews=new Collaboration(db),domains=new Domains(db,options.resolveTxt,options.domainProvider===undefined?undefined:options.domainProvider),analytics=new Analytics(db,options.analyticsSecret??process.env.STUDIO_ANALYTICS_SECRET),commerce=new Commerce(db,options.commerce??configuredCommerce()),permissions=new Permissions(db),releases=new Releases(db,configuredExternalPublishingProvider()??undefined,webhooks),ai=new AiOrchestrator(db,commands,options.aiProvider===undefined?databaseConfiguredProvider(db,'COPY'):options.aiProvider,options.aiProvider===undefined?databaseConfiguredProvider(db,'EDITOR'):options.aiProvider,options.aiProvider===undefined?databaseConfiguredProvider(db,'PLANNER'):options.aiProvider,options.aiProvider===undefined?databaseConfiguredProvider(db,'EDITOR'):options.aiProvider,cmsCommands,featurePolicy,aiGovernance),seoAi=new AiSeo(db,options.aiProvider===undefined?databaseConfiguredProvider(db,'COPY'):options.aiProvider,featurePolicy,aiGovernance),agentTools=new AgentTools(db,commands,cmsCommands,releases,featurePolicy),assets=new Assets(db,featurePolicy,aiGovernance,options.imageProvider===undefined?undefined:options.imageProvider),codeComponents=new CodeComponents(db,options.aiProvider===undefined?databaseConfiguredProvider(db,'CODE'):options.aiProvider,options.codeSandbox===undefined?configuredCodeSandboxProvider():options.codeSandbox,featurePolicy,aiGovernance),enterprise=new EnterpriseIdentity(db,options.oidcTransport,options.oidcSecretResolver),blog=new Blog(db),personalization=new Personalization(db,featurePolicy),quality=new Quality(db,options.visualValidation===undefined?undefined:options.visualValidation);
  router.use(observeStudioRequests,(_req,res,next)=>{res.setHeader('Cache-Control','no-store');next();});
  type Run=(req:Request,actor:Actor)=>Promise<Record<string,unknown>>;
  const route=(run:Run,status=200):RequestHandler=>async(req,res,next)=>{try{res.status(status).json({success:true,...await run(req,res.locals.actor)});}catch(e){next(e);}};
  const p=(req:Request,key:string)=>String(req.params[key]);
  // Must also precede the parent app's JSON parser. Never reconstruct bytes from parsed JSON.
  router.post('/payments/webhook',express.raw({type:'application/json',limit:'256kb'}),route(req=>commerce.webhook(req.body,req.get('Stripe-Signature'))));
  router.use(express.json({limit:'2mb'}));
  const oidcRate=rateLimit({windowMs:60000,limit:30,standardHeaders:true,legacyHeaders:false});
  const readCookie=(req:Request,name:string)=>req.headers.cookie?.split(';').map(v=>v.trim()).find(v=>v.startsWith(name+'='))?.slice(name.length+1);
  router.get('/oidc/:workspaceId/start',oidcRate,async(req,res,next)=>{
    try{
      const started=await enterprise.startOidc(p(req,'workspaceId'),req.query.returnTo);
      res.cookie('forge_oidc_pkce',`${started.stateId}.${started.verifier}`,{httpOnly:true,secure:process.env.NODE_ENV==='production',sameSite:'lax',path:`/api/v1/studio-next/oidc/${p(req,'workspaceId')}/callback`,maxAge:10*60*1000});
      res.redirect(302,started.authorizationUrl);
    }catch(error){next(error);}
  });
  router.get('/oidc/:workspaceId/callback',oidcRate,async(req,res,next)=>{
    try{
      const state=String(req.query.state||''),code=String(req.query.code||''),workspaceId=p(req,'workspaceId');
      const result=await enterprise.finishOidc(workspaceId,state,code,readCookie(req,'forge_oidc_pkce'));
      res.clearCookie('forge_oidc_pkce',{httpOnly:true,secure:process.env.NODE_ENV==='production',sameSite:'lax',path:`/api/v1/studio-next/oidc/${workspaceId}/callback`});
      res.cookie(AUTH_COOKIE_NAME,result.sessionToken,AUTH_COOKIE_OPTIONS);
      const origin=(process.env.FRONTEND_URL||'').replace(/\/$/,'');if(!origin)throw new StudioError('FRONTEND_URL is required after OIDC login',503,'OIDC_ORIGIN');
      res.redirect(302,origin+result.returnTo);
    }catch(error){next(error);}
  });
  const scim=express.Router();
  scim.use(rateLimit({windowMs:60000,limit:120,standardHeaders:true,legacyHeaders:false}));
  scim.get('/:workspaceId/Users',async(req,res,next)=>{try{res.json(await enterprise.listScim(String(req.params.workspaceId),req.get('Authorization'),typeof req.query.filter==='string'?req.query.filter:undefined));}catch(error){next(error);}});
  scim.post('/:workspaceId/Users',async(req,res,next)=>{try{res.status(201).json(await enterprise.createScim(String(req.params.workspaceId),req.get('Authorization'),req.body));}catch(error){next(error);}});
  scim.patch('/:workspaceId/Users/:externalId',async(req,res,next)=>{try{res.json(await enterprise.patchScim(String(req.params.workspaceId),String(req.params.externalId),req.get('Authorization'),req.body));}catch(error){next(error);}});
  router.use('/scim/v2',scim);
  const originGuard:RequestHandler=(req,res,next)=>{
    if(!['GET','HEAD','OPTIONS'].includes(req.method)&&(!trustedOrigin(req.get('Origin'),process.env.FRONTEND_URL,process.env.NODE_ENV==='production')||req.get('X-Studio-Request')!=='1'))return res.status(403).json({success:false,error:{code:'ORIGIN_REJECTED',message:'Request origin or request marker rejected'}});
    next();
  };
  const publicRouter=express.Router();
  publicRouter.use(rateLimit({windowMs:60000,limit:options.requestLimit??120,standardHeaders:true,legacyHeaders:false}));
  publicRouter.use(originGuard);
  publicRouter.post('/sites/:siteId/bindings/resolve',route(req=>cms.resolveBindings(p(req,'siteId'),parse(localeCode,req.query.locale??'en'),req.body)));
  publicRouter.get('/sites/:siteId/collections/:slug',route(req=>cms.publicItems(p(req,'siteId'),p(req,'slug'),parse(localeCode,req.query.locale??'en'))));
  publicRouter.get('/sites/:siteId/collections/:slug/:itemSlug',route(req=>cms.publicItems(p(req,'siteId'),p(req,'slug'),parse(localeCode,req.query.locale??'en'),p(req,'itemSlug'))));
  publicRouter.get('/sites/:siteId/localization',route(req=>localization.publicData(p(req,'siteId'),parse(localeCode,req.query.locale??'en'))));
  publicRouter.get('/sites/:siteId/localization/resolve',route(req=>localization.resolvePath(p(req,'siteId'),String(req.query.path??'/'))));
  publicRouter.get('/sites/:siteId/catalog',route(req=>commerce.catalog(p(req,'siteId'))));
  publicRouter.post('/sites/:siteId/checkout',route(req=>commerce.checkout(p(req,'siteId'),req.body),201));
  publicRouter.post('/sites/:siteId/checkout-cart',route(req=>commerce.checkoutCart(p(req,'siteId'),req.body),201));
  publicRouter.get('/sites/:siteId/analytics',route(req=>analytics.publicConfig(p(req,'siteId'))));
  publicRouter.post('/sites/:siteId/assignment',route(req=>analytics.assignment(p(req,'siteId'),req.body)));
  publicRouter.post('/sites/:siteId/events',route(req=>analytics.track(p(req,'siteId'),req.body),202));
  publicRouter.post('/sites/:siteId/personalization',route(req=>personalization.evaluate(p(req,'siteId'),req.body)));
  publicRouter.get('/sites/:siteId/blog/search',route(req=>blog.search(p(req,'siteId'),req.query)));
  publicRouter.get('/sites/:siteId/blog/posts/:slug',route(req=>blog.post(p(req,'siteId'),p(req,'slug'),parse(localeCode,req.query.locale??'en'))));
  publicRouter.get('/sites/:siteId/blog/authors/:slug',route(req=>blog.author(p(req,'siteId'),p(req,'slug'),parse(localeCode,req.query.locale??'en'))));
  publicRouter.get('/sites/:siteId/blog/categories/:slug',route(req=>blog.category(p(req,'siteId'),p(req,'slug'),parse(localeCode,req.query.locale??'en'))));
  publicRouter.get('/sites/:siteId/blog/rss.xml',async(req,res,next)=>{try{res.type('application/rss+xml').send(await blog.feed(p(req,'siteId'),parse(localeCode,req.query.locale??'en')));}catch(error){next(error);}});
  publicRouter.get('/sites/:siteId/blog/sitemap.xml',async(req,res,next)=>{try{res.type('application/xml').send(await blog.sitemap(p(req,'siteId'),parse(localeCode,req.query.locale??'en')));}catch(error){next(error);}});
  router.use('/public',publicRouter);
  router.use(db.auth(),originGuard,rateLimit({windowMs:60000,limit:options.requestLimit??360,keyGenerator:(_req:Request,res:Response)=>res.locals.actor.id,standardHeaders:true,legacyHeaders:false}));
  router.get('/workspaces/:workspaceId/enterprise-identity',route((req,a)=>enterprise.get(a,p(req,'workspaceId'))));
  router.put('/workspaces/:workspaceId/enterprise-identity',route((req,a)=>enterprise.configure(a,p(req,'workspaceId'),req.body)));
  router.post('/workspaces/:workspaceId/enterprise-identity/scim-token',route((req,a)=>enterprise.rotateScimToken(a,p(req,'workspaceId'))));
  router.get('/invitations',route((_req,a)=>workspaces.inbox(a)));
  router.post('/invitations/:invitationId/accept',route((req,a)=>workspaces.accept(a,p(req,'invitationId'))));
  router.get('/workspaces/:workspaceId/people',route((req,a)=>workspaces.list(a,p(req,'workspaceId'))));
  router.post('/workspaces/:workspaceId/invitations',route((req,a)=>workspaces.invite(a,p(req,'workspaceId'),req.body),201));
  router.patch('/workspaces/:workspaceId/invitations/:invitationId',route((req,a)=>workspaces.changeInvite(a,p(req,'workspaceId'),p(req,'invitationId'),req.body)));
  router.patch('/workspaces/:workspaceId/members/:userId',route((req,a)=>workspaces.changeMember(a,p(req,'workspaceId'),p(req,'userId'),req.body)));
  router.get('/sites/:siteId/ai/status',route((req,a)=>db.tx(async c=>{await db.site(c,a,p(req,'siteId'),'VIEW');return ai.status(p(req,'siteId'));})));
  router.get('/sites/:siteId/agent/tools',route((req,a)=>agentTools.catalog(a,p(req,'siteId'))));
  router.post('/sites/:siteId/agent/tools/:tool/execute',route((req,a)=>agentTools.execute(a,p(req,'siteId'),p(req,'tool'),req.body)));
  router.get('/sites/:siteId/governance/features',route((req,a)=>featurePolicy.list(a,p(req,'siteId'))));
  router.put('/sites/:siteId/governance/features',route((req,a)=>featurePolicy.set(a,p(req,'siteId'),req.body)));
  router.get('/sites/:siteId/governance/ai-budget',route((req,a)=>aiGovernance.report(a,p(req,'siteId'))));
  router.put('/sites/:siteId/governance/ai-budget',route((req,a)=>aiGovernance.setBudget(a,p(req,'siteId'),req.body)));
  router.get('/sites/:siteId/ai/code/status',route((req,a)=>codeComponents.status(a,p(req,'siteId'))));
  router.post('/sites/:siteId/ai/code/propose',route((req,a)=>codeComponents.propose(a,p(req,'siteId'),req.body),201));
  router.get('/sites/:siteId/assets/generation-status',route((req,a)=>assets.generationStatus(a,p(req,'siteId'))));
  router.post('/sites/:siteId/assets/generate',route((req,a)=>assets.generate(a,p(req,'siteId'),req.body),201));
  router.get('/sites/:siteId/ai/changes',route((req,a)=>ai.listChanges(a,p(req,'siteId'))));
  router.post('/sites/:siteId/ai/copy/propose',route((req,a)=>ai.proposeCopy(a,p(req,'siteId'),req.body),201));
  router.post('/sites/:siteId/ai/sections/propose',route((req,a)=>ai.proposeSection(a,p(req,'siteId'),req.body),201));
  router.post('/sites/:siteId/ai/pages/propose',route((req,a)=>ai.proposePage(a,p(req,'siteId'),req.body),201));
  router.post('/sites/:siteId/ai/sites/propose',route((req,a)=>ai.proposeSite(a,p(req,'siteId'),req.body),201));
  router.post('/sites/:siteId/ai/cms/propose',route((req,a)=>ai.proposeCms(a,p(req,'siteId'),req.body),201));
  router.post('/sites/:siteId/ai/seo/propose',route((req,a)=>seoAi.propose(a,p(req,'siteId'),req.body),201));
  router.post('/sites/:siteId/ai/changes/:changeSetId/apply',route((req,a)=>ai.apply(a,p(req,'siteId'),p(req,'changeSetId'))));
  router.post('/sites/:siteId/ai/changes/:changeSetId/reject',route((req,a)=>ai.reject(a,p(req,'siteId'),p(req,'changeSetId'))));
  router.get('/sites/:siteId/quality',route((req,a)=>quality.inspect(a,p(req,'siteId'),String(req.query.visual||'')==='true')));
  router.get('/sites/:siteId/blog',route((req,a)=>blog.status(a,p(req,'siteId'))));
  router.post('/sites/:siteId/blog/setup',route((req,a)=>blog.setup(a,p(req,'siteId')),201));
  router.get('/sites/:siteId/blog/preview/:slug',route((req,a)=>blog.preview(a,p(req,'siteId'),p(req,'slug'),parse(localeCode,req.query.locale??'en'))));
  router.get('/sites/:siteId/personalization',route((req,a)=>personalization.list(a,p(req,'siteId'))));
  router.post('/sites/:siteId/personalization',route((req,a)=>personalization.create(a,p(req,'siteId'),req.body),201));
  router.put('/sites/:siteId/personalization/:ruleId',route((req,a)=>personalization.update(a,p(req,'siteId'),p(req,'ruleId'),req.body)));
  router.patch('/sites/:siteId/personalization/:ruleId/state',route((req,a)=>personalization.state(a,p(req,'siteId'),p(req,'ruleId'),req.body)));
  router.delete('/sites/:siteId/personalization/:ruleId',route((req,a)=>personalization.remove(a,p(req,'siteId'),p(req,'ruleId'))));
  router.get('/sites/:siteId/collections',route((req,a)=>cms.collections(a,p(req,'siteId'))));
  router.post('/sites/:siteId/collections',route((req,a)=>cmsCommands.createCollection(a,p(req,'siteId'),req.body,{source:'HUMAN'}),201));
  router.put('/sites/:siteId/collections/:collectionId',route((req,a)=>cms.saveCollection(a,p(req,'siteId'),req.body,p(req,'collectionId'))));
  router.delete('/sites/:siteId/collections/:collectionId',route((req,a)=>cms.removeCollection(a,p(req,'siteId'),p(req,'collectionId'))));
  router.get('/sites/:siteId/collections/:collectionId/items',route((req,a)=>cms.items(a,p(req,'siteId'),p(req,'collectionId'),req.query)));
  router.get('/sites/:siteId/collections/:collectionId/options',route((req,a)=>cms.referenceOptions(a,p(req,'siteId'),p(req,'collectionId'))));
  router.post('/sites/:siteId/collections/:collectionId/items',route((req,a)=>cmsCommands.createItem(a,p(req,'siteId'),p(req,'collectionId'),req.body,{source:'HUMAN'}),201));
  router.post('/sites/:siteId/collections/:collectionId/import',route((req,a)=>cms.importItems(a,p(req,'siteId'),p(req,'collectionId'),req.body),201));
  router.put('/sites/:siteId/items/:itemId',route((req,a)=>cms.updateItem(a,p(req,'siteId'),p(req,'itemId'),req.body)));
  router.post('/sites/:siteId/items/:itemId/actions',route((req,a)=>cms.action(a,p(req,'siteId'),p(req,'itemId'),req.body)));
  router.get('/sites/:siteId/items/:itemId/revisions',route((req,a)=>cms.revisions(a,p(req,'siteId'),p(req,'itemId'))));
  router.post('/sites/:siteId/items/:itemId/restore',route((req,a)=>cms.restoreRevision(a,p(req,'siteId'),p(req,'itemId'),req.body)));
  router.get('/sites/:siteId/webhooks',route((req,a)=>webhooks.list(a,p(req,'siteId'))));
  router.post('/sites/:siteId/webhooks',route((req,a)=>webhooks.create(a,p(req,'siteId'),req.body),201));
  router.post('/sites/:siteId/webhooks/:endpointId/test',route((req,a)=>webhooks.test(a,p(req,'siteId'),p(req,'endpointId')),202));
  router.delete('/sites/:siteId/webhooks/:endpointId',route((req,a)=>webhooks.remove(a,p(req,'siteId'),p(req,'endpointId'))));
  router.post('/sites/:siteId/webhook-deliveries/:deliveryId/redeliver',route((req,a)=>webhooks.redeliver(a,p(req,'siteId'),p(req,'deliveryId')),202));
  router.get('/sites/:siteId/releases',route((req,a)=>releases.list(a,p(req,'siteId'))));
  router.post('/sites/:siteId/releases',route((req,a)=>releases.prepare(a,p(req,'siteId'),req.body),201));
  router.post('/sites/:siteId/releases/:releaseId/publish',route((req,a)=>releases.publish(a,p(req,'siteId'),p(req,'releaseId'))));
  router.post('/sites/:siteId/releases/:releaseId/rollback',route((req,a)=>releases.rollback(a,p(req,'siteId'),p(req,'releaseId')),201));
  router.get('/sites/:siteId/design',route((req,a)=>design.read(a,p(req,'siteId'))));
  router.put('/sites/:siteId/design',route((req,a)=>design.save(a,p(req,'siteId'),req.body)));
  router.post('/sites/:siteId/design/commands',route((req,a)=>commands.executeDesignCommands(a,p(req,'siteId'),req.body,{source:'HUMAN'})));
  router.get('/sites/:siteId/snapshots',route((req,a)=>design.snapshots(a,p(req,'siteId'))));
  router.post('/sites/:siteId/snapshots',route((req,a)=>design.capture(a,p(req,'siteId'),req.body),201));
  router.post('/sites/:siteId/snapshots/:snapshotId/restore',route((req,a)=>design.restore(a,p(req,'siteId'),p(req,'snapshotId'),req.body)));
  router.get('/sites/:siteId/locales',route((req,a)=>localization.locales(a,p(req,'siteId'))));
  router.put('/sites/:siteId/locales',route((req,a)=>localization.locales(a,p(req,'siteId'),req.body)));
  router.get('/sites/:siteId/localization',route((req,a)=>localization.list(a,p(req,'siteId'),parse(localeCode,req.query.locale??'en'))));
  router.put('/sites/:siteId/localization/:pageId/:locale',route((req,a)=>localization.save(a,p(req,'siteId'),p(req,'pageId'),p(req,'locale'),req.body)));
  router.post('/sites/:siteId/localization/:pageId/:locale/publish',route((req,a)=>localization.publish(a,p(req,'siteId'),p(req,'pageId'),p(req,'locale'),req.body)));
  router.get('/sites/:siteId/threads',route((req,a)=>reviews.threads(a,p(req,'siteId'))));
  router.post('/sites/:siteId/threads',route((req,a)=>reviews.create(a,p(req,'siteId'),req.body),201));
  router.patch('/sites/:siteId/threads/:threadId',route((req,a)=>reviews.change(a,p(req,'siteId'),p(req,'threadId'),req.body)));
  router.get('/sites/:siteId/domains',route((req,a)=>domains.list(a,p(req,'siteId'))));
  router.post('/sites/:siteId/domains',route((req,a)=>domains.add(a,p(req,'siteId'),req.body),201));
  router.post('/sites/:siteId/domains/:domainId/verify',route((req,a)=>domains.verify(a,p(req,'siteId'),p(req,'domainId'))));
  router.post('/sites/:siteId/domains/:domainId/provision',route((req,a)=>domains.provision(a,p(req,'siteId'),p(req,'domainId'),req.body)));
  router.post('/sites/:siteId/domains/:domainId/health',route((req,a)=>domains.refreshHosting(a,p(req,'siteId'),p(req,'domainId'))));
  router.delete('/sites/:siteId/domains/:domainId',route((req,a)=>domains.remove(a,p(req,'siteId'),p(req,'domainId'))));
  router.get('/sites/:siteId/permissions',route((req,a)=>permissions.list(a,p(req,'siteId'))));
  router.put('/sites/:siteId/permissions',route((req,a)=>permissions.set(a,p(req,'siteId'),req.body)));
  router.get('/sites/:siteId/products',route((req,a)=>commerce.products(a,p(req,'siteId'))));
  router.post('/sites/:siteId/products',route((req,a)=>commerce.saveProduct(a,p(req,'siteId'),req.body),201));
  router.put('/sites/:siteId/products/:productId',route((req,a)=>commerce.saveProduct(a,p(req,'siteId'),req.body,p(req,'productId'))));
  router.post('/sites/:siteId/refunds',route((req,a)=>commerce.refund(a,p(req,'siteId'),req.body),201));
  router.get('/sites/:siteId/analytics',route((req,a)=>analytics.settings(a,p(req,'siteId'))));
  router.put('/sites/:siteId/analytics',route((req,a)=>analytics.settings(a,p(req,'siteId'),req.body)));
  router.get('/sites/:siteId/analytics/report',route((req,a)=>analytics.report(a,p(req,'siteId'))));
  router.get('/sites/:siteId/experiments',route((req,a)=>analytics.experiments(a,p(req,'siteId'))));
  router.post('/sites/:siteId/experiments',route((req,a)=>analytics.createExperiment(a,p(req,'siteId'),req.body),201));
  router.patch('/sites/:siteId/experiments/:experimentId',route((req,a)=>analytics.changeExperiment(a,p(req,'siteId'),p(req,'experimentId'),req.body)));
  router.use((_req,res)=>res.status(404).json({success:false,error:{code:'NOT_FOUND',message:'Endpoint not found'}}));
  router.use((error:unknown,_req:Request,res:Response,_next:NextFunction)=>{
    const code=(error as any)?.code;
    let status=error instanceof StudioError?error.status:code==='23505'?409:['23503','23514','22P02'].includes(code)?400:['40001','40P01'].includes(code)?409:503;
    if((error as any)?.type==='entity.parse.failed')status=400;
    if((error as any)?.type==='entity.too.large')status=413;
    const message=error instanceof StudioError?error.message:status===409?'A conflicting record or concurrent change exists. Reload and retry.':status===400?'Invalid request or reference.':status===413?'Request too large.':'Site Studio is unavailable. Check connectivity and apply its reviewed migrations.';
    if(status===503)console.error('Site Studio request failed',{requestId:res.getHeader('X-Request-Id'),code:code||'UNKNOWN'});
    res.status(status).json({success:false,error:{code:error instanceof StudioError?error.code:status===409?'CONFLICT':'REQUEST_FAILED',message,requestId:res.getHeader('X-Request-Id')}});
  });
  return router;
}
