import {before,after,test} from 'node:test';
import {randomUUID} from 'node:crypto';
import assert from 'node:assert/strict';
import type pg from 'pg';
import type {Server} from 'node:http';
import {testPool,install,actor,site,serverFor,url,type TestActor} from './fixture.js';
import {Database} from '../../src/modules/studio-next/database.js';
import type {AIProvider} from '../../src/modules/studio-next/ai.js';

if(!url)test('AI integration requires STUDIO_TEST_DATABASE_URL',{skip:true},()=>{});
else {
  let pool:pg.Pool,server:Server,base:string,user:TestActor,siteId:string,calls=0;
  const provider:AIProvider={name:'fixture',model:'fixture-model-v1',async generateStructured(input){
    calls++;
    let value:any;
    if(input.system.includes('one editable website section'))value={section:{id:'ai-pricing',type:'section',children:[{id:'ai-pricing-title',type:'heading',content:'Simple pricing'}]},rationale:'Adds only the requested section.'};
    else if(input.system.startsWith('Generate one editable website page'))value={page:{id:'ai-about',name:'About AI',slug:'/about-ai',elements:[{id:'ai-about-heading',type:'heading',content:'About our product',styles:{fontSize:'40px'}}],pageSettings:{title:'About AI',description:'About this product'}},rationale:'Adds one page without changing existing pages.'};
    else if(input.system.includes('website architecture plan'))value={siteName:'Accounting Cloud',pages:[{id:'site-home',name:'Home',slug:'/',purpose:'Primary landing page'},{id:'site-features',name:'Features',slug:'/features',purpose:'Explain product features'},{id:'site-contact',name:'Contact',slug:'/contact',purpose:'Lead capture'}],designSystem:{variables:[{id:'ds-primary',name:'Primary',category:'color',token:'--fs-color-primary',value:'#2563eb'}],classes:[{id:'ds-card',name:'Card',className:'fs-card',styles:{borderRadius:'16px',padding:'24px'}}]}};
    else if(input.system.includes('approved site plan'))value={pages:[{id:'site-home',name:'Home',slug:'/',elements:[{id:'site-home-hero',type:'container',children:[{id:'site-home-title',type:'heading',content:'Accounting made clear'}]}],pageSettings:{title:'Accounting Cloud'}},{id:'site-features',name:'Features',slug:'/features',elements:[{id:'site-features-title',type:'heading',content:'Features'}],pageSettings:{title:'Features'}},{id:'site-contact',name:'Contact',slug:'/contact',elements:[{id:'site-contact-title',type:'heading',content:'Contact us'}],pageSettings:{title:'Contact'}}]};
    else value={replacement:'Concise heading',rationale:'Shorter without changing the claim.'};
    return {value,usage:{inputUnits:10,outputUnits:5}};
  }};
  const send=async(method:string,path:string,body?:unknown,expected=200)=>{
    const r=await fetch(base+path,{method,headers:{Cookie:`forge_session=${user.token}`,Origin:'http://localhost:5173','X-Studio-Request':'1',...(body!==undefined?{'Content-Type':'application/json'}:{})},...(body!==undefined?{body:JSON.stringify(body)}:{})});
    const value=await r.json();assert.equal(r.status,expected,`${method} ${path}: ${JSON.stringify(value)}`);return value;
  };
  before(async()=>{process.env.FRONTEND_URL='http://localhost:5173';process.env.NODE_ENV='test';pool=testPool();await install(pool);const db=new Database(pool);user=await actor(pool);siteId=await site(pool,user);({server}=serverFor(db,{aiProvider:provider,requestLimit:100000}));await new Promise<void>(resolve=>server.listen(0,'127.0.0.1',resolve));base=`http://127.0.0.1:${(server.address() as any).port}/api/v1/studio-next`;});
  after(async()=>{await new Promise<void>(resolve=>server.close(()=>resolve()));await pool.query('DELETE FROM public.users WHERE id=$1',[user.id]);await pool.end();});
  test('typed human commands mutate only their stable-ID targets',async()=>{const d=await send('GET',`/sites/${siteId}/design`);const op=randomUUID();await send('POST',`/sites/${siteId}/design/commands`,{baseHash:d.hash,operationId:op,commands:[{type:'SET_STYLE',elementId:'heading',property:'fontSize',value:'24px'},{type:'SET_ELEMENT_TEXT',elementId:'heading',field:'content',value:'Command heading'}]});const next=await send('GET',`/sites/${siteId}/design`);assert.equal(next.website.editorData.elements[0].content,'Command heading');assert.equal(next.website.editorData.elements[0].styles.fontSize,'24px');});
  test('typed command retries are idempotent and stale commands fail',async()=>{const d=await send('GET',`/sites/${siteId}/design`),operationId=randomUUID(),body={baseHash:d.hash,operationId,commands:[{type:'SET_ELEMENT_TEXT',elementId:'heading',field:'content',value:'Retry once'}]};const first=await send('POST',`/sites/${siteId}/design/commands`,body);const second=await send('POST',`/sites/${siteId}/design/commands`,body);assert.equal(first.hash,second.hash);assert.equal(second.replayed,true);await send('POST',`/sites/${siteId}/design/commands`,{...body,operationId:randomUUID()},409);});
  test('structural commands require stable unique IDs',async()=>{const d=await send('GET',`/sites/${siteId}/design`);await send('POST',`/sites/${siteId}/design/commands`,{baseHash:d.hash,operationId:randomUUID(),commands:[{type:'ADD_ELEMENT',parentId:null,afterId:'heading',element:{id:'cta-section',type:'section',children:[]}}]});const next=await send('GET',`/sites/${siteId}/design`);assert.equal(next.website.editorData.elements.at(-1).id,'cta-section');await send('POST',`/sites/${siteId}/design/commands`,{baseHash:next.hash,operationId:randomUUID(),commands:[{type:'ADD_ELEMENT',parentId:null,afterId:null,element:{id:'cta-section',type:'section'}}]},409);});
  test('page lifecycle commands preserve home and slug invariants',async()=>{
    const s=await site(pool,user,{version:1,elements:[],pages:[]},'DRAFT');let d=await send('GET',`/sites/${s}/design`);
    await send('POST',`/sites/${s}/design/commands`,{baseHash:d.hash,operationId:randomUUID(),commands:[{type:'CREATE_PAGE',page:{id:'page-home',name:'Home',slug:'/',elements:[{id:'page-home-title',type:'heading',content:'Home'}],pageSettings:{title:'Home'}}},{type:'CREATE_PAGE',page:{id:'page-about',name:'About',slug:'/about',elements:[{id:'page-about-title',type:'heading',content:'About'}],pageSettings:{title:'About'}}},{type:'SET_HOME_PAGE',pageId:'page-about'}]});
    d=await send('GET',`/sites/${s}/design`);assert.equal(d.website.editorData.homePageId,'page-about');assert.equal(d.website.editorData.pages.find((p:any)=>p.id==='page-about').slug,'/');assert.notEqual(d.website.editorData.pages.find((p:any)=>p.id==='page-home').slug,'/');
    await send('POST',`/sites/${s}/design/commands`,{baseHash:d.hash,operationId:randomUUID(),commands:[{type:'UPDATE_PAGE',pageId:'page-home',patch:{name:'Welcome',slug:'/welcome'}},{type:'REORDER_PAGES',pageIds:['page-about','page-home']}]});
    d=await send('GET',`/sites/${s}/design`);assert.deepEqual(d.website.editorData.pages.map((p:any)=>p.id),['page-about','page-home']);assert.equal(d.website.editorData.pages[1].name,'Welcome');
    await send('POST',`/sites/${s}/design/commands`,{baseHash:d.hash,operationId:randomUUID(),commands:[{type:'CREATE_PAGE',page:{id:'bad-slug',name:'Bad',slug:'/welcome',elements:[]}}]},409);
  });
  test('AI page generation is reviewable and generated content remains manually editable',async()=>{
    const s=await site(pool,user,{version:1,elements:[],pages:[]},'DRAFT');const before=await send('GET',`/sites/${s}/design`);
    const p=await send('POST',`/sites/${s}/ai/pages/propose`,{instruction:'Create an about page'},201);assert.equal(p.page.id,'ai-about');assert.equal((await send('GET',`/sites/${s}/design`)).website.editorData.pages.length,0);
    await send('POST',`/sites/${s}/ai/changes/${p.changeSetId}/apply`,{});let d=await send('GET',`/sites/${s}/design`);assert.equal(d.website.editorData.pages[0].id,'ai-about');assert.equal(d.website.editorData.pages[0].slug,'/');
    await send('POST',`/sites/${s}/design/commands`,{baseHash:d.hash,operationId:randomUUID(),commands:[{type:'SET_ELEMENT_TEXT',elementId:'ai-about-heading',field:'content',value:'Edited by a person'}]});d=await send('GET',`/sites/${s}/design`);assert.equal(d.website.editorData.pages[0].elements[0].content,'Edited by a person');assert.notEqual(before.hash,d.hash);
  });
  test('AI full-site generation plans, builds and applies editable pages plus a reusable design system',async()=>{
    const s=await site(pool,user,{version:1,elements:[],pages:[]},'DRAFT');const before=await send('GET',`/sites/${s}/design`);
    const proposal=await send('POST',`/sites/${s}/ai/sites/propose`,{instruction:'Create a professional accounting SaaS website'},201);assert.equal(proposal.pageCount,3);assert.equal(proposal.plan.pages.length,3);assert.equal((await send('GET',`/sites/${s}/design`)).website.editorData.pages.length,0);
    await send('POST',`/sites/${s}/ai/changes/${proposal.changeSetId}/apply`,{});let d=await send('GET',`/sites/${s}/design`);assert.equal(d.website.editorData.pages.length,3);assert.equal(d.website.editorData.homePageId,'site-home');assert.equal(d.website.editorData.globalVariables[0].id,'ds-primary');assert.equal(d.website.editorData.globalClasses[0].id,'ds-card');
    await send('POST',`/sites/${s}/design/commands`,{baseHash:d.hash,operationId:randomUUID(),commands:[{type:'SET_STYLE',elementId:'site-home-title',property:'fontSize',value:'56px'}]});d=await send('GET',`/sites/${s}/design`);assert.equal(d.website.editorData.pages[0].elements[0].children[0].styles.fontSize,'56px');assert.notEqual(before.hash,d.hash);
    await send('POST',`/sites/${s}/ai/sites/propose`,{instruction:'Replace the whole site'},409);
  });
  test('AI section generation creates a reviewable local changeset and remains manually editable',async()=>{const before=await send('GET',`/sites/${siteId}/design`);const p=await send('POST',`/sites/${siteId}/ai/sections/propose`,{instruction:'Add a simple pricing section',afterId:'heading'},201);assert.equal(p.section.id,'ai-pricing');assert.equal((await send('GET',`/sites/${siteId}/design`)).website.editorData.elements.some((x:any)=>x.id==='ai-pricing'),false);await send('POST',`/sites/${siteId}/ai/changes/${p.changeSetId}/apply`,{});let d=await send('GET',`/sites/${siteId}/design`);assert.equal(d.website.editorData.elements.some((x:any)=>x.id==='ai-pricing'),true);await send('POST',`/sites/${siteId}/design/commands`,{baseHash:d.hash,operationId:randomUUID(),commands:[{type:'SET_STYLE',elementId:'ai-pricing',property:'padding',value:'48px'}]});d=await send('GET',`/sites/${siteId}/design`);assert.equal(d.website.editorData.elements.find((x:any)=>x.id==='ai-pricing').styles.padding,'48px');assert.notEqual(before.hash,d.hash);});
  test('AI proposal is persisted but does not mutate the design until approval',async()=>{const callsBefore=calls;const before=await send('GET',`/sites/${siteId}/design`);const p=await send('POST',`/sites/${siteId}/ai/copy/propose`,{elementId:'heading',field:'content',instruction:'Make it concise'},201);assert.equal(p.replacement,'Concise heading');assert.equal((await send('GET',`/sites/${siteId}/design`)).website.editorData.elements[0].content,before.website.editorData.elements[0].content);await send('POST',`/sites/${siteId}/ai/changes/${p.changeSetId}/apply`,{});assert.equal((await send('GET',`/sites/${siteId}/design`)).website.editorData.elements[0].content,'Concise heading');assert.equal(calls,callsBefore+1);const receipt=await pool.query('SELECT source,command FROM studio.command_receipts WHERE idempotency_key=$1',[p.changeSetId]);assert.deepEqual(receipt.rows[0],{source:'AI',command:'design.save'});assert.notEqual(before.hash,(await send('GET',`/sites/${siteId}/design`)).hash);});
  test('applying an AI changeset is idempotent',async()=>{const p=await send('POST',`/sites/${siteId}/ai/copy/propose`,{elementId:'heading',field:'content',instruction:'Shorten again'},201);const first=await send('POST',`/sites/${siteId}/ai/changes/${p.changeSetId}/apply`,{});const second=await send('POST',`/sites/${siteId}/ai/changes/${p.changeSetId}/apply`,{});assert.equal(first.hash,second.hash);assert.equal(second.alreadyApplied,true);});
  test('rejected AI proposals cannot later be applied',async()=>{const p=await send('POST',`/sites/${siteId}/ai/copy/propose`,{elementId:'heading',field:'content',instruction:'Do not use this'},201);await send('POST',`/sites/${siteId}/ai/changes/${p.changeSetId}/reject`,{});await send('POST',`/sites/${siteId}/ai/changes/${p.changeSetId}/apply`,{},409);});
  test('stale AI proposals cannot overwrite a newer manual save',async()=>{const p=await send('POST',`/sites/${siteId}/ai/copy/propose`,{elementId:'heading',field:'content',instruction:'Another version'},201);const d=await send('GET',`/sites/${siteId}/design`);d.website.editorData.elements[0].content='Manual newer edit';await send('PUT',`/sites/${siteId}/design`,{baseHash:d.hash,editorData:d.website.editorData,operationId:randomUUID()});await send('POST',`/sites/${siteId}/ai/changes/${p.changeSetId}/apply`,{},409);assert.equal((await send('GET',`/sites/${siteId}/design`)).website.editorData.elements[0].content,'Manual newer edit');});
}
