import {before,after,describe,test} from 'node:test';
import assert from 'node:assert/strict';
import {randomUUID,createHmac} from 'node:crypto';
import type pg from 'pg';
import type {Server} from 'node:http';
import {WebSocket} from 'ws';
import {testPool,install,actor,site,workspace,grant,serverFor,url,type TestActor} from './fixture.js';
import {Database} from '../../src/modules/studio-next/database.js';
import {Cms} from '../../src/modules/studio-next/cms.js';
import {deliverInvitations} from '../../src/modules/studio-next/workspaces.js';
import {createPresenceServer} from '../../src/modules/studio-next/presence.js';
import type {CommerceConfig} from '../../src/modules/studio-next/commerce.js';

// Tests use real HTTP requests, database sessions and PostgreSQL; provider boundaries are explicit fakes.
describe('Site Studio authenticated HTTP and PostgreSQL integration',{skip:!url},()=>{
 let pool:pg.Pool,db:Database,server:Server,base:string,wss:ReturnType<typeof createPresenceServer>;
 const users:TestActor[]=[],sockets:WebSocket[]=[];const signing='test-webhook-secret';let dnsAnswer:string[][]=[];
 const commerce:CommerceConfig={origin:'http://localhost:5173',webhookSecret:signing,accounts:{},transport:async(_account,path,_method,body)=>path.startsWith('prices/')?{active:true,type:'one_time',currency:'usd',unit_amount:1000}:{id:`cs_${body!.get('client_reference_id')!.replaceAll('-','')}`,url:'https://checkout.stripe.com/c/pay/cs_fixture'}};
 const make=async(overrides:any={},status='ACTIVE')=>{const a=await actor(pool,overrides,status);users.push(a);return a;};
 async function send(method:string,path:string,a?:TestActor,body?:unknown,expected=200,headers:Record<string,string>={}){
   const r=await fetch(base+path,{method,headers:{...(a?{Cookie:`forge_session=${a.token}`} : {}),Origin:'http://localhost:5173','X-Studio-Request':'1',...(body!==undefined?{'Content-Type':'application/json'}:{}),...headers},...(body!==undefined?{body:JSON.stringify(body)}:{})});
   const value=await r.json();assert.equal(r.status,expected,`${method} ${path}: ${JSON.stringify(value)}`);return value;
 }
 async function collection(a:TestActor,s:string,fields:any[]=[{key:'body',name:'Body',type:'TEXT',required:true}],name='Articles'){
   return (await send('POST',`/sites/${s}/collections`,a,{name,slug:name.toLowerCase(),fields},201)).id as string;
 }
 async function item(a:TestActor,s:string,c:string,fields:any={body:'Live text'},name='One'){
   return (await send('POST',`/sites/${s}/collections/${c}/items`,a,{name,slug:name.toLowerCase(),fields},201)).id as string;
 }
 async function state(a:TestActor,s:string,c:string,id:string,locale='en'){return (await send('GET',`/sites/${s}/collections/${c}/items?locale=${locale}`,a)).items.find((i:any)=>i.id===id);}
 async function action(a:TestActor,s:string,c:string,id:string,act:string,extra:any={},expected=200){const current=await state(a,s,c,id);return send('POST',`/sites/${s}/items/${id}/actions`,a,{action:act,revision:current.revision,...extra},expected);}
 const publicItems=(s:string,name='articles',locale='en')=>send('GET',`/public/sites/${s}/collections/${name}?locale=${locale}`);
 before(async()=>{
   process.env.FRONTEND_URL='http://localhost:5173';process.env.NODE_ENV='test';delete process.env.STUDIO_SMTP_URL;
   pool=testPool();await install(pool);db=new Database(pool);
   ({server}=serverFor(db,{commerce,analyticsSecret:'test-analytics-signing-secret-at-least-32-chars',resolveTxt:async()=>dnsAnswer,requestLimit:100000}));
   wss=createPresenceServer(server,db);await new Promise<void>(resolve=>server.listen(0,'127.0.0.1',resolve));base=`http://127.0.0.1:${(server.address() as any).port}/api/v1/studio-next`;
 });
 after(async()=>{for(const s of sockets)s.terminate();for(const s of wss.clients)s.terminate();await new Promise<void>(resolve=>server.close(()=>resolve()));await pool.query('DELETE FROM public.users WHERE id=ANY($1::uuid[])',[users.map(a=>a.id)]);await pool.end();});
 test('unauthenticated API requests do not reveal site data',async()=>{await send('GET',`/sites/${randomUUID()}/collections`,undefined,undefined,401);});
 test('inactive and expired sessions are rejected',async()=>{const a=await make({},'SUSPENDED');await send('GET','/invitations',a,undefined,401);const b=await make();await pool.query('UPDATE public.sessions SET "expiresAt"=now()-interval \'1 second\' WHERE "userId"=$1',[b.id]);await send('GET','/invitations',b,undefined,401);});
 test('malformed session cookie is a bounded authentication error',async()=>{await send('GET','/invitations',undefined,undefined,401,{Cookie:'forge_session=%invalid'});});
 test('writes reject hostile origins and missing request markers',async()=>{const a=await make(),s=await site(pool,a);await send('POST',`/sites/${s}/collections`,a,{name:'X',slug:'x',fields:[]},403,{Origin:'https://evil.example'});await send('POST',`/sites/${s}/collections`,a,{name:'X',slug:'x',fields:[]},403,{'X-Studio-Request':''});});
 test('cross-tenant site reads and writes are rejected',async()=>{const a=await make(),b=await make(),s=await site(pool,a);await send('GET',`/sites/${s}/collections`,b,undefined,404);await send('POST',`/sites/${s}/collections`,b,{name:'Stolen',slug:'stolen',fields:[]},404);});
 test('workspace invite appears only in the matched verified inbox',async()=>{const a=await make(),b=await make(),stranger=await make(),w=await workspace(pool,a);const i=await send('POST',`/workspaces/${w}/invitations`,a,{email:b.email!.toUpperCase(),role:'MEMBER'},201);assert.equal(i.delivery,'NOT_CONFIGURED');assert.equal((await send('GET','/invitations',b)).invitations[0].id,i.id);assert.equal((await send('GET','/invitations',stranger)).invitations.length,0);await send('POST',`/invitations/${i.id}/accept`,stranger,{},404);});
 test('invitation acceptance uses real session identity and is idempotent',async()=>{const a=await make(),b=await make(),w=await workspace(pool,a);const i=await send('POST',`/workspaces/${w}/invitations`,a,{email:b.email,role:'MEMBER'},201);await send('POST',`/invitations/${i.id}/accept`,b,{});assert.equal((await send('POST',`/invitations/${i.id}/accept`,b,{})).alreadyAccepted,true);assert.equal((await pool.query('SELECT count(*)::int AS n FROM public.workspace_members WHERE "workspaceId"=$1 AND "userId"=$2',[w,b.id])).rows[0].n,1);});
 test('unverified accounts cannot accept invitations',async()=>{const a=await make(),b=await make({emailVerified:false}),w=await workspace(pool,a);const i=await send('POST',`/workspaces/${w}/invitations`,a,{email:b.email,role:'MEMBER'},201);assert.equal((await send('GET','/invitations',b)).requiresVerifiedEmail,true);await send('POST',`/invitations/${i.id}/accept`,b,{},403);});
 test('revoked and expired invitations cannot be accepted',async()=>{const a=await make(),b=await make(),c=await make(),w=await workspace(pool,a);const i=await send('POST',`/workspaces/${w}/invitations`,a,{email:b.email,role:'MEMBER'},201);await send('PATCH',`/workspaces/${w}/invitations/${i.id}`,a,{action:'REVOKE',revision:0});await send('POST',`/invitations/${i.id}/accept`,b,{},410);const j=await send('POST',`/workspaces/${w}/invitations`,a,{email:c.email,role:'MEMBER'},201);await pool.query('UPDATE studio.workspace_invites SET expires_at=now()-interval \'1 second\' WHERE id=$1',[j.id]);await send('POST',`/invitations/${j.id}/accept`,c,{},410);});
 test('resend respects cooldown and revision preconditions',async()=>{const a=await make(),b=await make(),w=await workspace(pool,a);const i=await send('POST',`/workspaces/${w}/invitations`,a,{email:b.email,role:'MEMBER'},201);await send('PATCH',`/workspaces/${w}/invitations/${i.id}`,a,{action:'RESEND',revision:0},429);await pool.query('UPDATE studio.workspace_invites SET updated_at=now()-interval \'2 minutes\' WHERE id=$1',[i.id]);await send('PATCH',`/workspaces/${w}/invitations/${i.id}`,a,{action:'RESEND',revision:0});await send('PATCH',`/workspaces/${w}/invitations/${i.id}`,a,{action:'REVOKE',revision:0},409);});
 test('workspace admins cannot appoint admins or remove the owner',async()=>{const a=await make(),b=await make(),w=await workspace(pool,a);await pool.query('INSERT INTO public.workspace_members(id,"workspaceId","userId",role) VALUES($1,$2,$3,\'ADMIN\')',[randomUUID(),w,b.id]);await send('POST',`/workspaces/${w}/invitations`,b,{email:'new@example.test',role:'ADMIN'},403);await send('PATCH',`/workspaces/${w}/members/${a.id}`,b,{role:'REMOVE'},403);});
 test('invites from an inactive inviter no longer grant access',async()=>{const a=await make(),b=await make(),w=await workspace(pool,a);const i=await send('POST',`/workspaces/${w}/invitations`,a,{email:b.email,role:'MEMBER'},201);await pool.query('UPDATE public.users SET status=\'SUSPENDED\' WHERE id=$1',[a.id]);await send('POST',`/invitations/${i.id}/accept`,b,{},403);});
 test('SMTP-disabled worker does not claim delivery',async()=>{assert.equal(await deliverInvitations(db),0);});
 test('new sites automatically receive the primary locale',async()=>{const a=await make(),s=await site(pool,a);assert.deepEqual((await send('GET',`/sites/${s}/locales`,a)).locales,[{code:'en',name:'English',enabled:true}]);});
 test('draft CMS records do not appear in public reads',async()=>{const a=await make(),s=await site(pool,a),c=await collection(a,s);await item(a,s,c);assert.equal((await publicItems(s)).items.length,0);});
 test('required field errors block publishing without blocking draft creation',async()=>{const a=await make(),s=await site(pool,a),c=await collection(a,s),i=await item(a,s,c,{});await action(a,s,c,i,'PUBLISH',{},400);assert.equal((await publicItems(s)).items.length,0);});
 test('publishing creates an immutable live snapshot while subsequent edits remain draft',async()=>{const a=await make(),s=await site(pool,a),c=await collection(a,s),i=await item(a,s,c);await action(a,s,c,i,'PUBLISH');const live=(await publicItems(s)).items[0];assert.equal(live.fields.body,'Live text');const st=await state(a,s,c,i);await send('PUT',`/sites/${s}/items/${i}`,a,{name:'Changed',slug:'changed',fields:{body:'Draft text'},revision:st.revision});assert.deepEqual((await publicItems(s)).items[0],live);await send('GET',`/public/sites/${s}/collections/articles/changed`,undefined,undefined,404);await action(a,s,c,i,'PUBLISH');assert.equal((await publicItems(s)).items[0].slug,'changed');});
 test('stale item edits and lifecycle actions cannot overwrite newer state',async()=>{const a=await make(),s=await site(pool,a),c=await collection(a,s),i=await item(a,s,c);await action(a,s,c,i,'READY');await send('PUT',`/sites/${s}/items/${i}`,a,{name:'Stale',slug:'stale',fields:{body:'bad'},revision:0},409);await send('POST',`/sites/${s}/items/${i}/actions`,a,{action:'PUBLISH',revision:0},409);});
 test('cross-site collection and item IDs are rejected',async()=>{const a=await make(),s1=await site(pool,a),s2=await site(pool,a),c=await collection(a,s1),i=await item(a,s1,c);await send('GET',`/sites/${s2}/collections/${c}/items`,a,undefined,404);await send('PUT',`/sites/${s2}/items/${i}`,a,{name:'x',slug:'x',fields:{body:'x'},revision:0},404);});
 test('content editors can save drafts but cannot change schema or publish by default',async()=>{const a=await make(),b=await make(),s=await site(pool,a);await grant(pool,s,b,'CONTENT_EDITOR');const c=await collection(a,s),i=await item(b,s,c);await send('POST',`/sites/${s}/collections`,b,{name:'No',slug:'no',fields:[]},403);await send('POST',`/sites/${s}/items/${i}/actions`,b,{action:'PUBLISH',revision:0},403);});
 test('populated schema cannot remove fields or mutate existing field types',async()=>{const a=await make(),s=await site(pool,a),c=await collection(a,s);await item(a,s,c);await send('PUT',`/sites/${s}/collections/${c}`,a,{name:'Articles',slug:'articles',fields:[],revision:0},409);await send('PUT',`/sites/${s}/collections/${c}`,a,{name:'Articles',slug:'articles',fields:[{key:'body',name:'Body',type:'NUMBER',required:true}],revision:0},409);});
 test('an empty collection may be deleted but a populated collection may not',async()=>{const a=await make(),s=await site(pool,a),c=await collection(a,s);await send('DELETE',`/sites/${s}/collections/${c}`,a,{});const d=await collection(a,s);await item(a,s,d);await send('DELETE',`/sites/${s}/collections/${d}`,a,{},409);});
 test('JSON import is atomic on a duplicate slug',async()=>{const a=await make(),s=await site(pool,a),c=await collection(a,s);await send('POST',`/sites/${s}/collections/${c}/import`,a,{items:[{name:'A',slug:'same',fields:{body:'a'}},{name:'B',slug:'same',fields:{body:'b'}}]},409);assert.equal((await send('GET',`/sites/${s}/collections/${c}/items`,a)).total,0);});
 test('CMS wildcard characters are literal search terms',async()=>{const a=await make(),s=await site(pool,a),c=await collection(a,s);await send('POST',`/sites/${s}/collections/${c}/items`,a,{name:'100% guide',slug:'guide',fields:{body:'text'}},201);await item(a,s,c);assert.equal((await send('GET',`/sites/${s}/collections/${c}/items?q=%25`,a)).total,1);});
 test('reference publication requires a live item in the same site',async()=>{const a=await make(),s=await site(pool,a),authors=await collection(a,s,[],'Authors'),author=await item(a,s,authors,{},'Author'),group=(await state(a,s,authors,author)).groupId;const c=await collection(a,s,[{key:'author',name:'Author',type:'REFERENCE',required:true,referenceCollection:authors}]),i=await item(a,s,c,{author:group});await action(a,s,c,i,'PUBLISH',{},400);await action(a,s,authors,author,'PUBLISH');await action(a,s,c,i,'PUBLISH');assert.equal((await publicItems(s)).items[0].fields.author,group);});
 test('CMS translations share a group, remain independent, and respect locale enablement',async()=>{const a=await make(),s=await site(pool,a),c=await collection(a,s),i=await item(a,s,c),group=(await state(a,s,c,i)).groupId;await send('PUT',`/sites/${s}/locales`,a,{code:'fr',name:'French',enabled:false});const french=await send('POST',`/sites/${s}/collections/${c}/items`,a,{name:'Bonjour',slug:'bonjour',locale:'fr',groupId:group,fields:{body:'Français'}},201);await send('POST',`/sites/${s}/items/${french.id}/actions`,a,{action:'PUBLISH',revision:0});assert.equal((await publicItems(s,'articles','fr')).items.length,0);await send('PUT',`/sites/${s}/locales`,a,{code:'fr',name:'French',enabled:true});assert.equal((await publicItems(s,'articles','fr')).items[0].groupId,group);assert.equal((await publicItems(s)).items.length,0);});
 test('archive immediately unpublishes content, and restore alone does not republish',async()=>{const a=await make(),s=await site(pool,a),c=await collection(a,s),i=await item(a,s,c);await action(a,s,c,i,'PUBLISH');await action(a,s,c,i,'ARCHIVE');assert.equal((await publicItems(s)).items.length,0);await action(a,s,c,i,'PUBLISH',{},409);await action(a,s,c,i,'RESTORE');assert.equal((await publicItems(s)).items.length,0);await action(a,s,c,i,'PUBLISH');assert.equal((await publicItems(s)).items.length,1);});
 test('revision restoration changes only the draft',async()=>{const a=await make(),s=await site(pool,a),c=await collection(a,s),i=await item(a,s,c);await action(a,s,c,i,'PUBLISH');await send('PUT',`/sites/${s}/items/${i}`,a,{name:'New',slug:'new',fields:{body:'new'},revision:1});await send('POST',`/sites/${s}/items/${i}/restore`,a,{revision:2,targetRevision:0});assert.equal((await state(a,s,c,i)).fields.body,'Live text');assert.equal((await publicItems(s)).items[0].name,'One');});
 test('scheduled publishing uses stored revision and the actual worker iteration',async()=>{const a=await make(),s=await site(pool,a),c=await collection(a,s),i=await item(a,s,c);await action(a,s,c,i,'SCHEDULE',{scheduledAt:new Date(Date.now()+60000).toISOString()});await pool.query('UPDATE studio.content_items SET scheduled_at=now()-interval \'1 second\' WHERE id=$1',[i]);assert.equal((await new Cms(db).publishDue()).published,1);assert.equal((await publicItems(s)).items.length,1);});
 test('scheduled publisher permission is checked again at execution time',async()=>{const a=await make(),b=await make(),s=await site(pool,a);await grant(pool,s,b,'DESIGNER');const c=await collection(a,s),i=await item(a,s,c);await action(b,s,c,i,'SCHEDULE',{scheduledAt:new Date(Date.now()+60000).toISOString()});await send('PUT',`/sites/${s}/permissions`,a,{userId:b.id,capability:'PUBLISH',effect:'DENY'});await pool.query('UPDATE studio.content_items SET scheduled_at=now()-interval \'1 second\' WHERE id=$1',[i]);assert.equal((await new Cms(db).publishDue()).cancelled,1);assert.equal((await publicItems(s)).items.length,0);});
 test('saving a scheduled draft cancels its pending publication',async()=>{const a=await make(),s=await site(pool,a),c=await collection(a,s),i=await item(a,s,c);await action(a,s,c,i,'SCHEDULE',{scheduledAt:new Date(Date.now()+60000).toISOString()});await send('PUT',`/sites/${s}/items/${i}`,a,{name:'Later',slug:'later',fields:{body:'later'},revision:1});assert.equal((await state(a,s,c,i)).scheduledAt,null);});
 test('draft pages are never exposed through the localization public API',async()=>{const a=await make(),s=await site(pool,a,undefined,'DRAFT');await send('GET',`/public/sites/${s}/localization`,undefined,undefined,404);});
 test('page localization has an independent draft/live lifecycle',async()=>{const a=await make(),s=await site(pool,a);await send('PUT',`/sites/${s}/locales`,a,{code:'fr',name:'French',enabled:true});await send('PUT',`/sites/${s}/localization/home/fr`,a,{revision:0,data:{title:'Bonjour',texts:{heading:'Bonjour'}}});assert.deepEqual((await send('GET',`/public/sites/${s}/localization?locale=fr`)).pages,{});await send('POST',`/sites/${s}/localization/home/fr/publish`,a,{revision:1,publish:true});assert.equal((await send('GET',`/public/sites/${s}/localization?locale=fr`)).pages.home.texts.heading,'Bonjour');await send('PUT',`/sites/${s}/localization/home/fr`,a,{revision:1,data:{title:'Changed',texts:{heading:'Brouillon'}}});assert.equal((await send('GET',`/public/sites/${s}/localization?locale=fr`)).pages.home.texts.heading,'Bonjour');});
 test('locale settings cannot disable the primary locale or reference nonexistent elements',async()=>{const a=await make(),s=await site(pool,a);await send('PUT',`/sites/${s}/locales`,a,{code:'en',name:'English',enabled:false},400);await send('PUT',`/sites/${s}/locales`,a,{code:'fr',name:'French',enabled:true});await send('PUT',`/sites/${s}/localization/home/fr`,a,{revision:0,data:{texts:{not_an_element:'no'}}},400);});
 test('designer hash prevents concurrent-session lost updates',async()=>{const a=await make(),s=await site(pool,a),d=await send('GET',`/sites/${s}/design`,a);const next={...d.website.editorData,elements:[{id:'heading',type:'heading',content:'New'}]};await send('PUT',`/sites/${s}/design`,a,{baseHash:d.hash,editorData:next});await send('PUT',`/sites/${s}/design`,a,{baseHash:d.hash,editorData:next},409);});
 test('designer saves preserve operational state and cannot publish by mass assignment',async()=>{const a=await make(),s=await site(pool,a,{elements:[],hostingConfig:{secret:'kept'},publishedData:{elements:[{content:'live'}]}}),d=await send('GET',`/sites/${s}/design`,a);assert.equal(d.website.editorData.hostingConfig,undefined);await send('PUT',`/sites/${s}/design`,a,{baseHash:d.hash,editorData:{elements:[],hostingConfig:{secret:'changed'},publishedData:{elements:[]}}});const row=(await pool.query('SELECT "editorData" FROM public.websites WHERE id=$1',[s])).rows[0].editorData;assert.equal(row.hostingConfig.secret,'kept');assert.equal(row.publishedData.elements[0].content,'live');});
 test('content-only designers cannot modify layout',async()=>{const a=await make(),b=await make(),s=await site(pool,a);await grant(pool,s,b,'CONTENT_EDITOR');const d=await send('GET',`/sites/${s}/design`,b);d.website.editorData.elements[0].content='Edited text';await send('PUT',`/sites/${s}/design`,b,{baseHash:d.hash,editorData:d.website.editorData});const newer=await send('GET',`/sites/${s}/design`,b);newer.website.editorData.elements[0].styles.color='#abcdef';await send('PUT',`/sites/${s}/design`,b,{baseHash:newer.hash,editorData:newer.website.editorData},403);});
 test('non-owner designers cannot modify protected components',async()=>{const a=await make(),b=await make(),s=await site(pool,a,{elements:[{id:'locked',isProtected:true,content:'Fixed'}]});await grant(pool,s,b,'DESIGNER');const d=await send('GET',`/sites/${s}/design`,b);d.website.editorData.elements[0].content='Changed';await send('PUT',`/sites/${s}/design`,b,{baseHash:d.hash,editorData:d.website.editorData},403);});
 test('duplicate IDs cannot conceal changes to protected components',async()=>{const a=await make(),b=await make(),s=await site(pool,a,{elements:[{id:'locked',isProtected:true,content:'Fixed'}]});await grant(pool,s,b,'DESIGNER');const d=await send('GET',`/sites/${s}/design`,b);d.website.editorData.elements.push({id:'locked',isProtected:true,content:'Changed duplicate'});await send('PUT',`/sites/${s}/design`,b,{baseHash:d.hash,editorData:d.website.editorData},403);});
 test('snapshot restore makes a recovery point and leaves publishing state untouched',async()=>{const a=await make(),s=await site(pool,a),snapshot=await send('POST',`/sites/${s}/snapshots`,a,{name:'Before'},201),d=await send('GET',`/sites/${s}/design`,a);await send('PUT',`/sites/${s}/design`,a,{baseHash:d.hash,editorData:{elements:[]}});const newer=await send('GET',`/sites/${s}/design`,a);await send('POST',`/sites/${s}/snapshots/${snapshot.id}/restore`,a,{baseHash:newer.hash});assert.equal((await send('GET',`/sites/${s}/design`,a)).website.editorData.elements[0].content,'Original heading');assert.equal((await send('GET',`/sites/${s}/snapshots`,a)).snapshots.length,2);assert.equal((await pool.query('SELECT status FROM public.websites WHERE id=$1',[s])).rows[0].status,'PUBLISHED');});
 test('permission overrides deny reads and cannot be changed by non-owners',async()=>{const a=await make(),b=await make(),s=await site(pool,a);await grant(pool,s,b,'ADMIN');await send('PUT',`/sites/${s}/permissions`,b,{userId:b.id,capability:'VIEW',effect:'ALLOW'},403);await send('PUT',`/sites/${s}/permissions`,a,{userId:b.id,capability:'VIEW',effect:'DENY'});await send('GET',`/sites/${s}/collections`,b,undefined,404);await send('PUT',`/sites/${s}/permissions`,a,{userId:b.id,capability:'VIEW',effect:'INHERIT'});await send('GET',`/sites/${s}/collections`,b);});
 test('review authors come from the session, and resolution is author/admin-only',async()=>{const a=await make({fullName:'Owner'}),b=await make({fullName:'Reviewer'}),s=await site(pool,a);await grant(pool,s,b,'REVIEWER');const thread=await send('POST',`/sites/${s}/threads`,a,{content:'Review this',elementId:'heading'},201);await send('POST',`/sites/${s}/threads`,b,{content:'Spoof',authorId:a.id},400);await send('PATCH',`/sites/${s}/threads/${thread.id}`,b,{content:'A reply'});await send('PATCH',`/sites/${s}/threads/${thread.id}`,b,{revision:0,resolved:true},403);await send('PATCH',`/sites/${s}/threads/${thread.id}`,a,{revision:0,resolved:true});const t=(await send('GET',`/sites/${s}/threads`,a)).threads[0];assert.equal(t.author,'Owner');assert.equal(t.replies[0].author,'Reviewer');assert.equal(t.resolved,true);});
 test('domain verification checks the issued TXT value and never claims hosting',async()=>{const a=await make(),s=await site(pool,a),record=await send('POST',`/sites/${s}/domains`,a,{hostname:`${randomUUID()}.example.com`},201);dnsAnswer=[['wrong']];assert.equal((await send('POST',`/sites/${s}/domains/${record.id}/verify`,a,{})).verified,false);await pool.query('UPDATE studio.verified_domains SET checked_at=now()-interval \'20 seconds\' WHERE id=$1',[record.id]);dnsAnswer=[[record.record.value.slice(0,10),record.record.value.slice(10)]];const verified=await send('POST',`/sites/${s}/domains/${record.id}/verify`,a,{});assert.equal(verified.verified,true);assert.equal(verified.hostingStatus,'NOT_PROVISIONED');});
 test('only one site can claim the same verified hostname',async()=>{const a=await make(),s1=await site(pool,a),s2=await site(pool,a),hostname=`${randomUUID()}.example.com`;const x=await send('POST',`/sites/${s1}/domains`,a,{hostname},201),y=await send('POST',`/sites/${s2}/domains`,a,{hostname},201);dnsAnswer=[[x.record.value]];await send('POST',`/sites/${s1}/domains/${x.id}/verify`,a,{});dnsAnswer=[[y.record.value]];await send('POST',`/sites/${s2}/domains/${y.id}/verify`,a,{},409);});
 async function product(a:TestActor,s:string,priceMinor=1000){return (await send('POST',`/sites/${s}/products`,a,{name:'Test product',description:'Fixture',priceMinor,currency:'usd',stripePriceId:'price_fixture',active:true},201)).id;}
 async function checkout(a:TestActor,s:string,p:string,key=randomUUID()){commerce.accounts[s]='platform';await send('POST',`/public/sites/${s}/checkout`,undefined,{productId:p,quantity:2,operationId:key},201);return key;}
 async function webhook(order:string,s:string,type='checkout.session.completed',overrides:any={},expected=200){const event={id:`evt_${randomUUID().replaceAll('-','')}`,type,data:{object:{id:`cs_${order.replaceAll('-','')}`,mode:'payment',payment_status:'paid',metadata:{studio_order_id:order,studio_site_id:s},client_reference_id:order,amount_total:2000,currency:'usd',...overrides}}};const raw=JSON.stringify(event),stamp=Math.floor(Date.now()/1000),signature=createHmac('sha256',signing).update(`${stamp}.${raw}`).digest('hex');const r=await fetch(base+'/payments/webhook',{method:'POST',headers:{'Content-Type':'application/json','Stripe-Signature':`t=${stamp},v1=${signature}`},body:raw});const value=await r.json();assert.equal(r.status,expected,JSON.stringify(value));return {event,raw,signature,stamp};}
 test('checkout is disabled for unconfigured sites',async()=>{const a=await make(),s=await site(pool,a),p=await product(a,s);await send('POST',`/public/sites/${s}/checkout`,undefined,{productId:p,quantity:1,operationId:randomUUID()},503);});
 test('checkout rejects client-supplied amounts and validates the provider price',async()=>{const a=await make(),s=await site(pool,a),p=await product(a,s,1200);commerce.accounts[s]='platform';await send('POST',`/public/sites/${s}/checkout`,undefined,{productId:p,quantity:1,operationId:randomUUID(),amount:1},400);await send('POST',`/public/sites/${s}/checkout`,undefined,{productId:p,quantity:1,operationId:randomUUID()},409);});
 test('checkout retries keep the same order and price snapshot',async()=>{const a=await make(),s=await site(pool,a),p=await product(a,s),order=await checkout(a,s,p);await checkout(a,s,p,order);assert.equal((await pool.query('SELECT count(*)::int AS n FROM studio.checkout_orders WHERE id=$1',[order])).rows[0].n,1);await send('POST',`/public/sites/${s}/checkout`,undefined,{productId:p,quantity:1,operationId:order},409);});
 test('only signed, matching paid events mark an order paid; webhook replay is idempotent',async()=>{const a=await make(),s=await site(pool,a),p=await product(a,s),order=await checkout(a,s,p);await send('POST','/payments/webhook',undefined,{},400);await webhook(order,s,'checkout.session.completed',{amount_total:1},409);assert.equal((await pool.query('SELECT state FROM studio.checkout_orders WHERE id=$1',[order])).rows[0].state,'CHECKOUT');const signed=await webhook(order,s);assert.equal((await pool.query('SELECT state FROM studio.checkout_orders WHERE id=$1',[order])).rows[0].state,'PAID');const replay=await fetch(base+'/payments/webhook',{method:'POST',headers:{'Content-Type':'application/json','Stripe-Signature':`t=${signed.stamp},v1=${signed.signature}`},body:signed.raw});assert.equal((await replay.json()).duplicate,true);});
 test('an expired event cannot demote an already-paid order',async()=>{const a=await make(),s=await site(pool,a),p=await product(a,s),order=await checkout(a,s,p);await webhook(order,s);await webhook(order,s,'checkout.session.expired');assert.equal((await pool.query('SELECT state FROM studio.checkout_orders WHERE id=$1',[order])).rows[0].state,'PAID');});
 test('analytics requires explicit consent and starts disabled',async()=>{const a=await make(),s=await site(pool,a);assert.equal((await send('GET',`/public/sites/${s}/analytics`)).enabled,false);await send('POST',`/public/sites/${s}/assignment`,undefined,{visitorId:randomUUID(),path:'/',consent:true},403);await send('PUT',`/sites/${s}/analytics`,a,{enabled:true});await send('POST',`/public/sites/${s}/assignment`,undefined,{visitorId:randomUUID(),path:'/',consent:false},400);});
 test('analytics tickets are site-bound and events are deduplicated',async()=>{const a=await make(),s=await site(pool,a),s2=await site(pool,a);await send('PUT',`/sites/${s}/analytics`,a,{enabled:true});const assignment=await send('POST',`/public/sites/${s}/assignment`,undefined,{visitorId:randomUUID(),path:'/',consent:true});const body={id:randomUUID(),ticket:assignment.ticket,event:'PAGEVIEW'};await send('POST',`/public/sites/${s}/events`,undefined,body,202);await send('POST',`/public/sites/${s}/events`,undefined,body,202);await send('POST',`/public/sites/${s2}/events`,undefined,body,403);assert.equal((await send('GET',`/sites/${s}/analytics/report`,a)).daily[0].views,1);});
 test('conversions need a preceding pageview and invalid signatures are rejected',async()=>{const a=await make(),s=await site(pool,a);await send('PUT',`/sites/${s}/analytics`,a,{enabled:true});const x=await send('POST',`/public/sites/${s}/assignment`,undefined,{visitorId:randomUUID(),path:'/',consent:true});await send('POST',`/public/sites/${s}/events`,undefined,{id:randomUUID(),ticket:x.ticket,event:'CONVERSION'},409);await send('POST',`/public/sites/${s}/events`,undefined,{id:randomUUID(),ticket:x.ticket+'bad',event:'PAGEVIEW'},403);});
 test('experiment assignments are stable and lifecycle is constrained',async()=>{const a=await make(),s=await site(pool,a);await send('PUT',`/sites/${s}/analytics`,a,{enabled:true});const e=await send('POST',`/sites/${s}/experiments`,a,{name:'Headline',path:'/',targetElementId:'heading',variants:[{id:'a',label:'A',weight:50,text:'A text'},{id:'b',label:'B',weight:50,text:'B text'}]},201);await send('PATCH',`/sites/${s}/experiments/${e.id}`,a,{state:'RUNNING',revision:0});const body={visitorId:randomUUID(),path:'/',consent:true};assert.deepEqual((await send('POST',`/public/sites/${s}/assignment`,undefined,body)).variant,(await send('POST',`/public/sites/${s}/assignment`,undefined,body)).variant);await send('PATCH',`/sites/${s}/experiments/${e.id}`,a,{state:'CONCLUDED',revision:1});await send('PATCH',`/sites/${s}/experiments/${e.id}`,a,{state:'RUNNING',revision:2},409);});
 test('presence rejects unauthenticated websocket upgrades',async()=>{
   const target=base.replace('http:','ws:').split('/api/')[0]+'/ws/presence';
   await new Promise<void>((resolve,reject)=>{const ws=new WebSocket(target,{origin:'http://localhost:5173'});sockets.push(ws);ws.on('unexpected-response',(_r,res)=>{assert.equal(res.statusCode,401);res.resume();ws.terminate();resolve();});ws.on('open',()=>reject(new Error('Unauthenticated upgrade accepted')));ws.on('error',()=>{});});
 });
 test('presence ignores spoofed client identity and enforces site access',async()=>{
   const a=await make({fullName:'Real Person'}),s=await site(pool,a);const target=base.replace('http:','ws:').split('/api/')[0]+'/ws/presence';
   await new Promise<void>((resolve,reject)=>{const ws=new WebSocket(target,{origin:'http://localhost:5173',headers:{Cookie:`forge_session=${a.token}`}});sockets.push(ws);const timeout=setTimeout(()=>reject(new Error('Presence timeout')),5000);ws.on('open',()=>ws.send(JSON.stringify({type:'JOIN',websiteId:s,user:{id:randomUUID(),name:'Spoofed'}})));ws.on('message',data=>{const message=JSON.parse(data.toString());if(message.type==='SYNC'){try{assert.equal(message.peers[0].user.userId,a.id);assert.equal(message.peers[0].user.name,'Real Person');clearTimeout(timeout);ws.close();resolve();}catch(e){reject(e);}}});ws.on('error',reject);});
 });
});
